### ISSUE TITLE
Some settings lost on upgrade from 7.4.2 to 8.2.2

### ISSUE THREAD

**Issue by TheIronWolfModding** [zegreatclan/SimHub#1234]
**Describe the bug**
Moving from 7.4.2 to 8.2.2 lost few settings, luckily I had backup:

* Had to restore precalibration file:  "SimHub\ShakeItPrecalibration\GameData.json"
* Had to restore shifter bindings in: "PluginsData\Common\ShakeITBassShakersSettings.json"
* Minor: Missed gearshift effect could use some hint that Controller Input plugin has to be enabled for it to work.

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi ! 

Let's take it in order ;)
- About GameData.json it comes preinstalled with simhub installer, it's not a user file as is. If you change it it will indeed get lost. The goal of this file is to give a common baseline for all the installations independently of the automatic calibration process.

- Concerning the bindings it was indeed a known issue when coming to 7.X.X, I've maintained a self upgrade/downgrade process during a few months and removed it on the recent version. It was complexifying all the mapping saving process and making settings files much bigger than needed. 8.1.3 was the last "key version" able to upgrade the mappings from "one action to one input" to "one action to many inputs" and not getting them lost. I usually avoid such breaking changes and keep the self upgrade processes for years, but this particular case was too heavy to keep it so long.

- About missed gearshift , I added last year this resume of all the available inputs source, maybe it's not clear enough (The struggle of knowing :D, you don't see anymore where it fails :D ) I'm open to ideas about this :D .
![image](https://user-images.githubusercontent.com/2207331/221347336-c9f6bb18-9802-41f8-8ebd-ecf5b96dc06a.png)
