### ISSUE TITLE
AMS2 wrong damage values 

### ISSUE THREAD

**Issue by FullPace** [zegreatclan/SimHub#1344]
I'm building a dashboard to display  damge in AMS2 but the value don't match at all.

Here are two screenshots, Simhub and Ingame for comparison

![damage-ingame](https://github.com/SHWotever/SimHub/assets/116221480/dfb80132-8be2-430b-98dc-8134811eee83)
![SimHubWPF_D0DxrhBPgW](https://github.com/SHWotever/SimHub/assets/116221480/ccc7a6cd-b44e-43b7-a959-c77d126d8663)

**Comment by SHWotever** [comment]
Hi ! Everything shown in raw data is given straight by the game with no processing there is nothing I can change here I'm sorry. 

Telemetry often gives a "raw value" (IE going from 0 to 100) while UI could show a 100% damage as 20% raw damage for instance. 

Overall handling damages across games is extremely hard , it's the most inconsistent thing I've seen across simulators, units, ranges, locations, types, it's really unusable. Even tire wear can fall in such culprit (AC for instance has this issue)

**Comment by FullPace** [comment]
thanks for the heads up. I feared that. I‘ll bother Reiza with the issue 😁

**Comment by SHWotever** [comment]
No problems ;)
