### ISSUE TITLE
Web overlays made with StreamElements aren't showing up in a WebPageItem

### ISSUE THREAD

**Issue by fixfactory** [zegreatclan/SimHub#1386]
**Describe the bug**
I'm trying to show my Twitch viewer count and event list in a SimHub overlay using a WebPageItem. However, the page fails to render and appears blank. 

When the StreamElement URL is opened in a web browser or in OBS, it renders correctly.

**Simhub version**
SimHub v8.4.10 (build time : 04/08/2023 00:45:03)

**To Reproduce**
1. Create a new overlay
2. Add a 'Web page' item from the Toolbox
3. Set the property 'StartAddress' to https://streamelements.com/overlay/64d024f6ec961124d50c48ad/c4VXDV2u5lz4nu8sOu6yJGT7GSMTaauX0PcG_Y1skR5O1EHT
4. See that the page does not render.

**Expected behavior**
Expecting to see the Twitch event list, like we do when opening the URL in a web browser or in OBS.

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12282838/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! I checked, apparently once it's in an iframe (even in a regular chrome) or in the simhub custom browser (cefsharp) it shows nothing anymore, the browser console shows no error and the page content is loaded correctly (despite it does not get alive). 
I can't see any reasons except that the rendering is restricted to a complete browser or specifically OBS. I tried to check streamelements for their requirements, but apparently they only show OBS compatibility, there is no mention of browsers, iframe, or anything else.
