### ISSUE TITLE
Add computed fuel strategy like F1 2017

### ISSUE THREAD

**Issue by zegreatclan** [zegreatclan/SimHub#195]
Add computed fuel strategy like F1 2017 = a value that shows if you can finish the race and helps you knowing if you have to fuel save or not
P.S Doing a simple math operation doesn t work: when i cross the like it gives me for example +1 lap. when i am about to finish this lap it gives me 0.2 laps or something like that. Then it will get again +1 lap when i cross the line and finish the lap

**Comment by manuelbiancolilla21** [comment]
distanza1=$prop('DataCorePlugin.GameRawData.Data.mLapDist')
distanza2=$prop('DataCorePlugin.GameRawData.CurrentPlayer.mLapDist')
distanza3=distanza2/distanza1
giribenza=$prop('DataCorePlugin.Computed.Fuel_RemainingLaps')
girigara=$prop('DataCorePlugin.GameData.NewData.RemainingLaps')
sottrazione=(giribenza-girigara)*-1
risultato=distanza3-sottrazione
function roundup(num,dec){
    dec= dec || 0;
    s=String(num);
    if(num%1)s=s.replace(/5$/, '6');
    return Number((+s).toFixed(dec));
}
risultatoappr=roundup(risultato,2);

if((risultatoappr>0)&&(risultatoappr<1)||(risultatoappr>1))
return "+" + risultatoappr + " Laps";
if((risultatoappr>0.99)&&(risultatoappr<1.01))
return "+" + risultatoappr + " Lap";
if((risultatoappr<(-0.99))&&(risultatoappr>(-1.01)))
return risultatoappr + " Lap";
if((risultatoappr<0)&&(risultatoappr>(-1))||(risultatoappr<(-1)))
return risultatoappr + " Laps";
@zegreatclan done it by myself and with google. currently works on rf2, didnt test other games
