### ISSUE TITLE
Arduino Nano --> button box with matrix inputs

### ISSUE THREAD

**Issue by gegewrc** [zegreatclan/SimHub#237]
Hi guys!

I would like to use an Arduino nano in order to get a MAX7221 segment module (already integrated in the sketch setup) and to control a buttonbox with many buttons. I don't have enough inputs on the nano so I wish I could use a matrix like the attachment project below.
Would it be possible to add that in the main sketch setup? choose wich inputs and the characters in output. I am a noob in "arduino code" so I don't know if what I asked is possible or not... and if it's easy or if it's going to take hours of work....

![button_box_bb](https://user-images.githubusercontent.com/37621982/37709399-61886bb6-2d0a-11e8-87a8-706a1909d068.png)
 

https://www.xsimulator.net/community/threads/diy-arduino-buttonbox.8302/

**Comment by zegreatclan** [comment]
Hi !

Sadly the nano is not a HID compliant board (gamepad or keyboard) so it's not possible to make it output some characters.

I'm planning at a time to have fully configurable input management, but it would be best to use it with an arduino micro which is HID compliant.

**Comment by gegewrc** [comment]
Hi zegreatclan,

Thanks for this very very fast answer  :-).
I'm totally new to the arduino world so I didn't know the nano was not HID compliant...
As suggested, I will use a arduino UNO which I already use for controlling the RUMBLE PEDALS SIM RACING | SHAKE IT system  (https://www.youtube.com/watch?v=8aLqqcEaUVk&t=432s) or if not possible, I'll buy a new one.
Good to know that you plan to work on a fully configurable input management... It will make me spare a lot of wires and soldering   ;-).

Have a nice day.

**Comment by zegreatclan** [comment]
Until something comes to Simhub, somebody pointed me this solution recently : https://opensimhardware.wordpress.com/pedal-button-controller/

It just looks perfect !

**Comment by gegewrc** [comment]
Exactly what I was looking for until it comes to simhub...

Thanks for the tip!

**Comment by zegreatclan** [comment]
This have been added for the next version !

**Comment by gegewrc** [comment]
Thanks a lot!

**Comment by SmashinGSuViDm** [comment]
Здравствуйте, ребята помоги написать скетч для ардуино леонардо или про микро, как в данной теме, но мне нужно добавить три педали в данный проект. Можно ли совместить 25 кнопок и 3 педли в одном скетче. я плохо разбираюсь в программировании ардуино.
Hello, guys, help me write a sketch for Arduino Leonardo or about micro, as in this topic, but I need to add three pedals to this project. Can I combine 25 buttons and 3 loops in one sketch? I don't know much about Arduino programming.

**Comment by SmashinGSuViDm** [comment]
также, у меня есть скетч на 32 кнопки и отдельно на педали, но я вынужден освободить порт usb и для этого хотел бы сделать один контроллер на кнопки и педали, но у меня не получается правильно это соеденить програмно. #include <Joystick.h>

Joystick_ Joystick;
                    
int RyAxis_ = 0;  
int RzAxis_ = 0;          
int Throttle_ = 0;         

const bool initAutoSendState = true; 

void setup()
{
      Joystick.begin();
  }
   
void loop(){
  
 RyAxis_ = analogRead(A2);
 RyAxis_ = map(RyAxis_,0,1023,0,255);
 Joystick.setRyAxis(RyAxis_);

 RzAxis_ = analogRead(A3);
 RzAxis_ = map(RzAxis_,1023,0,255,0);            
Joystick.setRzAxis(RzAxis_);
  
Throttle_ = analogRead(A4);
Throttle_ = map(Throttle_,1023,0,255,0);         
Joystick.setThrottle(Throttle_);                
 
delay (50);
}


и
#include <Keypad.h>
#include <Joystick.h>

#define ENABLE_PULLUPS
#define NUMROTARIES 4
#define NUMBUTTONS 24
#define NUMROWS 5
#define NUMCOLS 5


byte buttons[NUMROWS][NUMCOLS] = {
  {0,1,2,3,4},
  {5,6,7,8,9},
  {10,11,12,13,14},
  {15,16,17,18,19},
  {20,21,22,23},
};

struct rotariesdef {
  byte pin1;
  byte pin2;
  int ccwchar;
  int cwchar;
  volatile unsigned char state;
};

rotariesdef rotaries[NUMROTARIES] {
  {0,1,24,25,0},
  {2,3,26,27,0},
  {4,5,28,29,0},
  {6,7,30,31,0},
};

#define DIR_CCW 0x10
#define DIR_CW 0x20
#define R_START 0x0

#ifdef HALF_STEP
#define R_CCW_BEGIN 0x1
#define R_CW_BEGIN 0x2
#define R_START_M 0x3
#define R_CW_BEGIN_M 0x4
#define R_CCW_BEGIN_M 0x5
const unsigned char ttable[6][4] = {
  // R_START (00)
  {R_START_M,            R_CW_BEGIN,     R_CCW_BEGIN,  R_START},
  // R_CCW_BEGIN
  {R_START_M | DIR_CCW, R_START,        R_CCW_BEGIN,  R_START},
  // R_CW_BEGIN
  {R_START_M | DIR_CW,  R_CW_BEGIN,     R_START,      R_START},
  // R_START_M (11)
  {R_START_M,            R_CCW_BEGIN_M,  R_CW_BEGIN_M, R_START},
  // R_CW_BEGIN_M
  {R_START_M,            R_START_M,      R_CW_BEGIN_M, R_START | DIR_CW},
  // R_CCW_BEGIN_M
  {R_START_M,            R_CCW_BEGIN_M,  R_START_M,    R_START | DIR_CCW},
};
#else
#define R_CW_FINAL 0x1
#define R_CW_BEGIN 0x2
#define R_CW_NEXT 0x3
#define R_CCW_BEGIN 0x4
#define R_CCW_FINAL 0x5
#define R_CCW_NEXT 0x6

const unsigned char ttable[7][4] = {
  // R_START
  {R_START,    R_CW_BEGIN,  R_CCW_BEGIN, R_START},
  // R_CW_FINAL
  {R_CW_NEXT,  R_START,     R_CW_FINAL,  R_START | DIR_CW},
  // R_CW_BEGIN
  {R_CW_NEXT,  R_CW_BEGIN,  R_START,     R_START},
  // R_CW_NEXT
  {R_CW_NEXT,  R_CW_BEGIN,  R_CW_FINAL,  R_START},
  // R_CCW_BEGIN
  {R_CCW_NEXT, R_START,     R_CCW_BEGIN, R_START},
  // R_CCW_FINAL
  {R_CCW_NEXT, R_CCW_FINAL, R_START,     R_START | DIR_CCW},
  // R_CCW_NEXT
  {R_CCW_NEXT, R_CCW_FINAL, R_CCW_BEGIN, R_START},
};
#endif

byte rowPins[NUMROWS] = {21,20,19,18,15}; 
byte colPins[NUMCOLS] = {14,16,10,9,8}; 

Keypad buttbx = Keypad( makeKeymap(buttons), rowPins, colPins, NUMROWS, NUMCOLS); 

Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, 
  JOYSTICK_TYPE_JOYSTICK, 32, 0,
  false, false, false, false, false, false,
  false, false, false, false, false);

void setup() {
  Joystick.begin();
  rotary_init();}

void loop() { 

  CheckAllEncoders();

  CheckAllButtons();

}

void CheckAllButtons(void) {
      if (buttbx.getKeys())
    {
       for (int i=0; i<LIST_MAX; i++)   
        {
           if ( buttbx.key[i].stateChanged )   
            {
            switch (buttbx.key[i].kstate) {  
                    case PRESSED:
                    case HOLD:
                              Joystick.setButton(buttbx.key[i].kchar, 1);
                              break;
                    case RELEASED:
                    case IDLE:
                              Joystick.setButton(buttbx.key[i].kchar, 0);
                              break;
            }
           }   
         }
     }
}


void rotary_init() {
  for (int i=0;i<NUMROTARIES;i++) {
    pinMode(rotaries[i].pin1, INPUT);
    pinMode(rotaries[i].pin2, INPUT);
    #ifdef ENABLE_PULLUPS
      digitalWrite(rotaries[i].pin1, HIGH);
      digitalWrite(rotaries[i].pin2, HIGH);
    #endif
  }
}


unsigned char rotary_process(int _i) {
   unsigned char pinstate = (digitalRead(rotaries[_i].pin2) << 1) | digitalRead(rotaries[_i].pin1);
  rotaries[_i].state = ttable[rotaries[_i].state & 0xf][pinstate];
  return (rotaries[_i].state & 0x30);
}

void CheckAllEncoders(void) {
  for (int i=0;i<NUMROTARIES;i++) {
    unsigned char result = rotary_process(i);
    if (result == DIR_CCW) {
      Joystick.setButton(rotaries[i].ccwchar, 1); delay(50); Joystick.setButton(rotaries[i].ccwchar, 0);
    };
    if (result == DIR_CW) {
      Joystick.setButton(rotaries[i].cwchar, 1); delay(50); Joystick.setButton(rotaries[i].cwchar, 0);
    };
  }
}

каждый из них работает отдельно, а совместить и сделать так ,что бы пк определил это как игровой контроллер у меня не получается... Если вы можите помочь мне я буду вам благодарен.
