### ISSUE TITLE
Request/question : virtual buttonbox

### ISSUE THREAD

**Issue by gegewrc** [zegreatclan/SimHub#244]
Hi!
I'm wondering if any template of a virtual buttonbox  does exist in the dash studio? 
Something like the roccat soft (http://www.isrtv.com/pc-racing/motec-button-box-using-free-roccat-power-grid/)  or like the slimax app. It would be nice to control all the mods (intensity of the rpm leds, gear indictaor,...) with virtual buttons.

Thank you.

![aa](https://user-images.githubusercontent.com/37621982/39721559-3996e33e-5240-11e8-83fc-ef17d9d9fe1e.jpg)

**Comment by zegreatclan** [comment]
Hi ! Sorry for the very late replay, I usually reply faster than that but I don't know why I missed your question, 

There is a button support indeed in dash studio, you can put your buttons, and choose to trigger an action/or a key press, the "weakness" would be that there is no predefined styles for the button you have to choose your pictures, there is a sample of that in the "mlobile dash" provided with simhub :
![image](https://user-images.githubusercontent.com/2207331/40764173-476f417a-64a8-11e8-94bf-b1140a4e4fbf.png)

**Comment by gegewrc** [comment]
No problem! Thanks for your time. I'll try to create a template and post it if it's not too bad!
