### ISSUE TITLE
Grrrrr. Bloody iRacing

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/SimHub#273]
Hey,

Just updated to latest simhub and now the following is missing:

[DataCorePlugin.GameRawData.Telemetry.dcEnginePower]

[DataCorePlugin.GameRawData.Telemetry.EnterExitReset]

[DataCorePlugin.GameRawData.Telemetry.dcFuelMixture]

[DataCorePlugin.GameRawData.Telemetry.dcTractionControl2]

[DataCorePlugin.GameRawData.Telemetry.dcThrottleShape]

[DataCorePlugin.GameRawData.Telemetry.PlayerCarTeamIncidentCount]

[DataCorePlugin.GameRawData.Telemetry.PlayerCarMyIncidentCount]

I'm sure there are more, I think a lot have gone missing :(

**Comment by Meekstaaa** [comment]
oh

[DataCorePlugin.GameRawData.Telemetry.PlayerCarClassPosition]

**Comment by Meekstaaa** [comment]
aha! It's kinda working now. Some properties have returned.

running a car now with this property working before but not now.

[DataCorePlugin.GameRawData.Telemetry.dcEnginePower]

it has 8 settings on the switch. Here's a little replay on track scrolling through the switch

[HPD.zip](https://github.com/zegreatclan/AssettoCorsaTools/files/2383940/HPD.zip)

**Comment by zegreatclan** [comment]
It should be good now, let me know if you have any other issues, otherwise I can close this one :D
