### ISSUE TITLE
Renaming replays breaks them

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/SimHub#278]
Hey,

Assume this is a bug. I've renamed my replays so I know which one is which and when I put just one in the folder it doesn't work.

If I put a non re-named replay back in the folder it works fine.

Just an FYI really.

**Comment by zegreatclan** [comment]
Yeah indeed simhub looks for the proper filename pattern and won't see it if you rename it, I really need to add a "replay manager" that's the real solution
