### ISSUE TITLE
Possible malfunction

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/SimHub#280]
![image](https://user-images.githubusercontent.com/28536883/46670470-964d0200-cbd2-11e8-8a28-023c98a5ef57.png)
Users have reported that in the latest version the Plugin was not loaded. To resolve the issue they have disabled and then re-enabled the plugin in the SimHub configuration.

**Comment by zegreatclan** [comment]
Could you send logs or any way to reproduce it ? I don't think it's a specific issue related to latest simhub as those core functions did not changed at all for long.

**Comment by TGD-Simracing** [comment]
I think the better way is to test it. Download the software from www.tgdsimware.com/navigator and test it.
I will provide more infos if I get into the issue. Thanks.

**Comment by zegreatclan** [comment]
Ok. I let you reopen a new issue when you will have enough informations. Currently there is nothing I can work on I'm afraid.
