### ISSUE TITLE
L298 can support 4 motors instead of 2

### ISSUE THREAD

**Issue by lshachar** [zegreatclan/SimHub#285]
Hey!
Since we don't care about shaker motor's direction of rotation, a single L298 can support 4 motors, in 4 half-bridge setup: any single motor is connected to an output on one side, and to either Vcc or ground on the other side (ground for the sake of this example). the two EN pins are pulled high (no need to take an arduino pin for that). the 4 IN pins on the L298 will control motor power - so they will need to be connected to PWM output pins on the arduino.
I guess that the only downside is several more advanced settings options in simhub

**Comment by zegreatclan** [comment]
I will add a new entry for direct PWM outputs (1 to 4 outputs) so it will be possible to do this layout without touching the code and it will also allow some custom made wirings such as PWM fans, tip 120 ....
I think it's a good compromise, what do you think about it ?

**Comment by lshachar** [comment]
I think you're one heck of a responsive dev!
yes, a direct PWM output option sounds very elegant! (although wouldn't expect most people to use that if they didn't have a couple of concrete examples - how to wire a pwm output to a transistor, or how to use an H bridge as 4 separate transistors.)

**Comment by zegreatclan** [comment]
Released with latest beta ;)

**Comment by SpeedBoy248** [comment]
Hi I need to know how to wire the the l298n to an arduino nano to have four outputs

**Comment by lshachar** [comment]
> Hi I need to know how to wire the the l298n to an arduino nano to have four outputs

Hi, I think I explained it quite well in my initial comment, please be more specific about your issue...
Also, please use 'please' and 'thank you' :)   sounds like you're demanding help, instead of asking for it! ;)

**Comment by SpeedBoy248** [comment]
I want to have 4 channels to control 4 motors with separate effects(2 for pedals and 2 for the seat) instead of 2 so I want to know the wiring because I don't understand it in your comment.
Thanks in Advance :)

**Comment by lshachar** [comment]
![image](https://user-images.githubusercontent.com/13820621/71580999-eed82a00-2b0b-11ea-9760-b6e6b5772ebf.png)
Does this help?

**Comment by SpeedBoy248** [comment]
![IC-L298_m](https://user-images.githubusercontent.com/59199876/71617266-fe667a00-2bc2-11ea-995a-268237f1973d.jpg)
I suppose that this is l298 chip but I can't find pin 16 and pins are not as the datasheet you uploaded
please be more I specific

Thanks for replying :)

**Comment by lshachar** [comment]
![image](https://user-images.githubusercontent.com/13820621/71631212-262fff00-2c10-11ea-914a-197f5f97112a.png)

**Comment by SpeedBoy248** [comment]
Thank you so much for your help!! 

Just couple more questions. 
1) Should I connect the input pins to pwm pins on arduino or any digital pin should work?
2) I think logic supply voltage(+5v) (pin 9) should be connected to 5v on arduino and power supply (5v-48v)connected to (pin 4). 
3) Shouldn't Enable pins connect to arduino pins instead of 5v?
4) Is this wiring will make the motors spin at various speeds(according to effects in game) or (ON and OFF) scenario?

Sorry for asking a lot of questions, I need to know everything before I throw money into parts 😀
Thanks again for your help.
Happy new year 😉

**Comment by lshachar** [comment]
1.PWM
2.yes, you are correct, I made a mistake before.
3. You need to connect the enable pins to 5V. (connect it to the logic power supply pin).
4.connect the input pins to PWM outputs on the arduino and you will get variable speeds.

**Comment by SpeedBoy248** [comment]
What a fast response!!
Another question I forgot 😅
Current sensing A and B pins (1 and 15), Should they be conneted to anything or not?
Thanks.

**Comment by lshachar** [comment]
disconnected.

**Comment by SpeedBoy248** [comment]
Thanks so much bro for you're help
I will try to upload an update as soon as I complete this project successfully
Happy New Year 🎊
