### ISSUE TITLE
How to Fix High CPU usage? I use SimHub just for Shakelt in Iracing

### ISSUE THREAD

**Issue by Marche777** [zegreatclan/SimHub#288]
Yesterday I installed the full version oh SimHub to use it as a valid alternative to SimVibe with Iracing.
After a lot of tweaking now my Shakers are working very well and the feedback is very good but there's only one problem... I can't run SimHub in backgroud or frame rates in VR fall drastically and the game becomes unplayable.
It happens in every online sessions.
I've checked the sistems loads and i found that SimHub use the 25/30% of my CPU power ( I5-7400), the RAM and the GPU loads are fine (16gb ddr4 and GTX 1070Ti).

Is there any way to fix this ENORMOUS cpu usage? I want to use it just for shaking my bass shakers. SimVibe use just 2-3% of the cpu...

I've already disabled every plugins under the settings menu and tried the higher process priority option without success.

Please, can someone help me?

Andrea

**Comment by zegreatclan** [comment]
Hi ! Could you send me the log files available in c:\Program Files (x86)\SimHub\Logs, such a high cpu is indeed not normal and it should not go above 3 or 5% for shakers , I use two dash (one web + one desktop), shakers and arduino for less than 6%.

Aslo make sure to disable the "live preview" since maintaining all these graphs can be quite hungry : 
![image](https://user-images.githubusercontent.com/2207331/47607090-cfcb9d00-da1b-11e8-938e-55c17d1ce493.png)

**Comment by zegreatclan** [comment]
Hi ! I'm affraid the attachments are not sent when using mail replies, could you attach them in github directly ?

**Comment by Marche777** [comment]
Oh sure! 
They are sixteen. I don't know what they are so i send you all, sorry...

Thank you

[Logs.zip](https://github.com/zegreatclan/SimHub/files/2522035/Logs.zip)

**Comment by zegreatclan** [comment]
No problems ! I've made some tests and I found an obvious leakage on iracing reader, it was not so visible on my machine, but performance traces clearly points it
I've built a beta version with a fix, could you come back to me and if it solves your problems ?
Here a dowload link :
http://www.simhubdash.com/downloads/SimHubSetup_6.6.0.exe




Nicolas

**Comment by Marche777** [comment]
Sure Nicolas, thank you.
I'm not at home now, let me try it few times tomorrow and i'll give you a
feedback asap. Do i have to unistall my already installed version?

Andrea



Il Sab 27 Ott 2018, 21:05 Wotever <notifications@github.com> ha scritto:

**Comment by zegreatclan** [comment]
You just have to install this version over it, it will keep your settings, no need to uninstall before ;)

From my tests I keep in the 2-3% range on my 7700k while I was more on a 15-20% trend before (and usually performances leak grows exponentionally with less CPU power which would match your 25-30% seen.

**Comment by Marche777** [comment]
*Problem solved!*
Now the CPU load for SimHub stays between 2 to 6%.

I've made a short video <https://we.tl/t-1NszliX6Tf> of my CPU loads during
half of a lap in Le Mans (the most heavy track in the game) to show you how
SimHub behaves.
In any case the last week i bought an i7-7700k and i'm waiting for it to
arrive next week, with it i should solve any issue, hopefully...

Thank you a lot Nicolas!

Il giorno sab 27 ott 2018 alle ore 21:34 Wotever <notifications@github.com>
ha scritto:

**Comment by zegreatclan** [comment]
Perfect ! Thanks for the feedback !
