### ISSUE TITLE
[Troubleshoot] Aftermarket Tacho wrong voltage

### ISSUE THREAD

**Issue by cazzoo** [zegreatclan/SimHub#291]
Hello there!

First of all I'd like to thank you for the job you do and the application you provide (including all the documentation).

I'm currently trying integrate aftermarker tacho gauge to my SIM and I'm encountering weird issues.
Following this wiki page for wirering I did created my custom board, replicating the schema to it, and I'm facing weird issues.

Here are the links to the parts I use:
* [Tacho](https://fr.aliexpress.com/item/Defi-Tachym-tre-Jauge-7-couleurs-0-11000-RPM-L-ger-D-calage-BF-style-Auto/32866412322.html?spm=a2g0s.9042311.0.0.27426c378ZmrUJ)
* [TIP120](https://fr.aliexpress.com/item/Free-shipping-50Pcs-Lot-TIP120-TO220-Transistor-TIP-120-NPN/32440462763.html?spm=a2g0w.search0104.3.1.13bb36fazB6BDD&ws_ab_test=searchweb0_0,searchweb201602_1_10065_10068_319_10892_317_10696_5728811_453_10084_454_10083_10618_10304_10307_10820_10821_537_10302_536_10843_5730111_5733211_328_5733311_10059_10884_5732711_5733411_10887_100031_5731011_321_322_10103_10913_10912_5733611_5729111_5733111_5733511-10892,searchweb201603_55,ppcSwitch_0&algo_expid=1b9d37d7-7ad3-4326-81a6-6f3f5935ff6f-0&algo_pvid=1b9d37d7-7ad3-4326-81a6-6f3f5935ff6f)
* [12V 1W zener diode](https://fr.aliexpress.com/item/2V4-to-33V-270-Pcs-27-Values-1W-Zener-Diode-Assorted-kit-Assortment-Set-New/32570858981.html?spm=a2g0s.9042311.0.0.27426c378ZmrUJ)
* 2.2kOhm
* [12V 2A power supply](https://fr.aliexpress.com/item/100-240V-AC-to-DC-Power-Adapter-Supply-Charger-adapter-5V-12V-1A-2A-3A-0/32825005194.html?spm=a2g0s.9042311.0.0.79276c378WObHS)

The tacho itself boots. I'm able to play with it using external buttons and such. That a good first step.

Then, I plugged-in to my arduino UNO, uploaded corresponding code using simHub and tried the "minMax" function but I was not able to get my tacho to move...
After trying to troubleshoot my issue using the wiki (https://github.com/zegreatclan/SimHub/wiki/Arduino-After-Market-Tach-support), I figured out that my power source voltage is correct (12V) but the others are wrong (7.4 instead of 2.5 to 3.0V)...

Do you think this could be my issue?
Might you have an idea why my build is not working (did you ever experienced it?)

Thank you for any reply.
Regards

**Comment by zegreatclan** [comment]
Hi ! I've never seen such issues. Indeed 7.4 V is a lot, maybe have you reversed the diode polarity ?

Concerning the tach like I said on the wiki there are many models, and it's not assured that they would work with this wiring, However currently you have a real issue with your wiring, if you measure more than 5V on the arduino (test#2) You definitely have a short or an issue in the wiring. The difficulty will be to ensure you have not fried anything now (arduino or tach).

Nicolas

**Comment by zegreatclan** [comment]
Edit : I've seen the aliexpress link , it's the "same" that the one I use personally (I put quotes because they all looks the same, but they are not necessary the same) .  They are cheap and a bit slow, but except defective tachs out of box, i've never seen much issues with theses. Really you should double check your wiring ;)

**Comment by cazzoo** [comment]
Hi Nicolas,

Thanks for the feedback.
I was actually thinking the same regarding the wiring. I'm pretty confident with the overall state of the tach or arduino since both still works as expected on their own (with other applications than tacho interface).

I think wiring looks good ([here is a photo of it](https://ibb.co/b1d2tV), and [here one with wiring details](https://ibb.co/hyKmLA)), the only thing that may be wrong could be diode polarity, but I plugged black ring to the power source, right after the TIP120.

I'll try tonight reversing the diode, just to see what's happening...
So far, thanks for support

**Comment by zegreatclan** [comment]
hi, I was reading again your part list, you used a zener diode, it's not the same component as a diode. It could be your issue ;)

**Comment by cazzoo** [comment]
Hi Nicolas,

That's correct but I'm rather disappointed because I hardly find a "standard" diode over aliexpress... 

That might be the issue here, I didn't had time yesterday and I will not have today neither to reverse the diode direction and test what will occur.

I'll double check if the zener could achieve the same job as the generic one.

**Comment by cazzoo** [comment]
Sorry for lack of response, I was heavily sick this week. 

I tried tonight unsolder and solder back again the zener diode. I checked validity of the diode too and everything was ok so far.

I wired the Boost gauge too (based on youtube video from amstudio) and I'm getting also a weird buzzer sound, which makes it barely untestable.

I uploaded a video on youtube showing what's happening for my rig : [here](https://www.youtube.com/watch?v=8VHoTXLl9Us).
In order to I changed power supply from 12V 2A to 12V 1A and I still have the same issue.

I also ordered a standard diode but It's slow shipping so I'm still testing with current zener diodes I have.
If you might have some time to look at the following video. Thanks in advance.

**Comment by zegreatclan** [comment]
There is definitely something weird happening on your arduino, the boost gauge takes 0 to 5v signal, really a basic wiring, 0=-5v while 5v = 2bars, on my arduino it can't even reach 5v (it's more 4.8 - 4.9) which does not allows to go above 1.8bars. here we can see that it goes straight to 2bars and you have the boost gauge overpressure beeping.  Basically it's strict the same issue as the RPM gauge, Could you measure the signal at the output of arduino ? For the boost you should have 0v when simhub is not running and arduino just plugged, Approximately 2.5 when zeroed with simhub running and "test 0" enabled. 

Also make sure to use the correct signal pin, on my boost it was the center wire on the sensor cable.

**Comment by zegreatclan** [comment]
Maybe a stupid question but it was not obvious even by looking at the video, does the gnd of the arduino is correctly connected to the gnd (-) of the power supply ?

**Comment by cazzoo** [comment]
Yes all ground cables are connected together. Power supply, arduino ground and tacho gauge

**Comment by cazzoo** [comment]
I will test tomorrow after work about the arduino voltage. I keep you in touch. Thanks for help so far

**Comment by cazzoo** [comment]
Tested just right now, with the power supply disconnected.
I measure 2.03 when "boost zero", 0 when "boost min" and 4.2 when "boost max" on the boost pin (5 in my case).
On the tach gauge I cannot measure any voltage, even when "testing max RPM" since my power supply is unplugged.
When plugging I'm getting 6.43V for tacho and 5V for boost no mater what I click on...

**Comment by zegreatclan** [comment]
So we start to get around something, the values you measured are correct when the power supply is disconnected. So we know signal is ok, there is something seriously guilty in the wiring. I think we must take back from the roots, starting with the boost only (as it doesn't require any PCB or such a thing) could you try to start with this one alone totally disconnected to the tach "PCB" . Then we will be sure that this is ok. Then could you send me detailed pictures of your tach PCB (both sides) I really feel 12v is sent somewhere where it should not go

**Comment by cazzoo** [comment]
I just tested right now and I'm really surprised because with the Boost gauge only and no sensor wire connected I'm getting same "bip" issue I had previously.
I plugged-in only GND, red (12v) and white (ignition) wires and it's behaving the same...
I tried with red and GND wires only and the boost doesn't boot up.
Tried also to plug white (ignition) wire only one time over 12v and then leaving red + gnd but it's stopping after a while.
I tried also red + yellow (illumination) with same cases than before but same results as before....

I'm really surprised about how it's acting....

I double checked wiring schema but it seems correct regarding my own wiring...
![img_20181122_183624 1](https://user-images.githubusercontent.com/1876754/48917237-07483080-ee86-11e8-92a6-db5fd136ef93.jpg)

**Comment by zegreatclan** [comment]
If it's just the "bip" it's probably the low pressure alert (there are low and high pressure alerts), it can be configured using the small button on the  back, you probably have instructions in the manual about how to configure it, I've done mine about one year ago and I lost the manual :D

**Comment by cazzoo** [comment]
Ok I've been a little bit further in the problem. I successfully set the boost gauge up so i'm able to stay next to it to test it.
I put my voltage metter in between my arduino GND and my pin out and noticed that :
- When Power supply is disconnected, voltage is correct and moves when I click on "test" buttons (min, 0, max)
- When power supply is connected, voltage value is always 5

Any ideas ?

Maybe we could switch to discord if it might be more convinient to talk ?

**Comment by cazzoo** [comment]
Hi @SHWotever ,
I finally got my tachometer working, but only when removing 12V Zener Diode.
When removed, the V on the green wire changes when the RPM changes, otherwise, with the  diode, the voltage is always set to 10.4. I tried to reverse the diode (without the gauge and with no load) but it doesn't work either.

Do you know if this could be an issue to run without the Diode or not ? I got the gauge working on two different titles with no issues.

**Comment by SHWotever** [comment]
Hi ! The diode is part of the "good practices" for such kind of electronic wiring, but it's not required for low consumption applications like this one.
