### ISSUE TITLE
Devices connected to analog ports don't show in wiring diagram picture (Arduino Nano)

### ISSUE THREAD

**Issue by Rovexx** [zegreatclan/SimHub#292]
I have connected a button and a some WS2812B leds to analog ports 15 and 14 (A0 and A1), but this doesnt show in the very nice wiring diagram picture on the right.
the I2C LCD SDA and SCL connections do show up at the analog ports A4 and A5.

I am using an Arduino Nano.

**Comment by zegreatclan** [comment]
Hi !

I've just checked I could not see the error : 
![image](https://user-images.githubusercontent.com/2207331/48507755-19eeb400-e84d-11e8-98f2-1e79a9d72cc3.png)

Could you export the profile when it's configured so I can check how the tool is considering the pins ?
![image](https://user-images.githubusercontent.com/2207331/48507794-34289200-e84d-11e8-93f1-07e8f76deea1.png)

**Comment by Rovexx** [comment]
Here you go, I use a lot of things so it could be that just as a heads up. 
I put the file in a .zip so I could upload it to Github:
[Simhub 6.6.0 beta 2.zip](https://github.com/zegreatclan/SimHub/files/2582359/Simhub.6.6.0.beta.2.zip)

**Comment by Rovexx** [comment]
I think it has to do with the fact that i loaded up a profile from an older version. when I recreate the profile from scratch it shows up correctly.

**Comment by zegreatclan** [comment]
Ah ok ! I see pin for leds was set on A1 in the profile, which was tolerated in older setup tool versions, while the new version only accepts numbers
I've converted it to numbers
[Simhub 6.6.0 beta 2.zip](https://github.com/zegreatclan/SimHub/files/2582414/Simhub.6.6.0.beta.2.zip)

Sadly i wont be able to load this syntax anymore (a0 ... a1), but I will make sure it does not get stuck is it does right now.

**Comment by Rovexx** [comment]
Awesome, thank you. I really appriciate your work. 
Keep up the good work and ill keep expanding my setup.

**Comment by zegreatclan** [comment]
I've fixed the tool, invalid values will now be resetted to default for next version.
