### ISSUE TITLE
Accessing another plugins properties from custom plugin

### ISSUE THREAD

**Issue by ahiscox** [zegreatclan/SimHub#295]
I'm writing a custom plugin for vibration motors, and I need to access the FeedbackValue_WheelLock ( brakes) and FeedbackValue_GasWheelSlide (gas pedal) properties from the ShakeItPlugin. Assuming I've identified the right properties for these pedals, is it possible to get access to these in my own plugin? I've tried playing around with pluginManager but I'm not very good with C# and had no luck. 

Thanks!

**Comment by zegreatclan** [comment]
Seen on discord, it required to use the full name (plugin name.propertyname) in GrtPropertyValue method
