### ISSUE TITLE
I hope to increase the differential lock prompt for "European Truck Simulator 2"

### ISSUE THREAD

**Issue by Lang-EVO** [zegreatclan/SimHub#297]
When I used the W2812 to refit the instrument, I found that in the ETS2 database, I did not find the option of differential lock. I hope I can increase it. Thank you very much.

**Comment by zegreatclan** [comment]
Hi ! I'm affraid that this data is not given by the ETS2 SDK ,currently all the data which can be accessible are already exposed, and anything else is not accessible, I'm sorry.

**Comment by Lang-EVO** [comment]
Thank you for your answer.
