### ISSUE TITLE
关于舵机仪表的问题

### ISSUE THREAD

**Issue by Lang-EVO** [zegreatclan/SimHub#300]
HI!Can I use the steering gear's own DIY meter so that it can be fully compatible?

**Comment by zegreatclan** [comment]
I'm affraid I've not understood your question. Could you explain ?

**Comment by Lang-EVO** [comment]
Maybe Google Translate is a bit incomplete, or the meaning is not the same. The steering gear I mentioned is the direction machine used to control the direction in the RC model.

**Comment by zegreatclan** [comment]
You mean servo motors like this ? 
![image](https://user-images.githubusercontent.com/2207331/49104877-6e4b5800-f27f-11e8-8b56-6ee18dd7af36.png)

**Comment by Lang-EVO** [comment]
Yes, it is also possible to replace the locking rudder with a faster and higher performance helicopter model.

**Comment by zegreatclan** [comment]
Hi ! I'm sorry I've already tried servo motors in the past and I ended by removing them, smoothness and noise were really unsupportable. It's not something I want to suggest to users again,

**Comment by Lang-EVO** [comment]
HI, I don't agree with this point of view, because there is better performance of the steering gear, can be used in the response time of no load 0.06S, I think this steering gear can do the work of the instrument.

**Comment by Lang-EVO** [comment]
![_20181129202853](https://user-images.githubusercontent.com/45336689/49222057-d0d65c80-f415-11e8-88c5-93ab6bb0d99b.png)

**Comment by zegreatclan** [comment]
Indeed those kind of models would probably work better, but the price of those is really unreasonable compared to the final use (above 30$ from what I can see), one of my objectives is to keep supported hardware accessible for a fair price. Something like the X27.168 steppers motors suggested here : https://github.com/zegreatclan/SimHub/issues/299 is more reasonable (about 1.5€ per motors) and will give a real automotive grade result in my opinion.

**Comment by Lang-EVO** [comment]
Is this stepper motor driven with L298? If there is a faster stepper motor, it is better.
