### ISSUE TITLE
Issues with my LCD and i2c

### ISSUE THREAD

**Issue by Nilmab100** [zegreatclan/SimHub#301]
I actually trying to display on 20×4 LCD i2c, I am using the address 0×3F gotten for the i2c scanner but it is not displaying what should do to solve this issue?

**Comment by zegreatclan** [comment]
Hi ! Have you gone through the whole setup guide ? https://github.com/zegreatclan/SimHub/wiki/Arduino-20x4-I2C-LCD I've updated it yesterday with more advices about the screen

If despite all the advices it still doesn't show anything, it means you probably have an incompatible model (see the warning on the wiki). Sadly these screens despite all looking the same work very inconsistently. 
In this case you can follow those instructions about submitting library for a new model : https://github.com/zegreatclan/SimHub/wiki/Arduino-20x4-I2C-LCD#what-if-your-screen-model-is-not-supported-after-all-tests.
