### ISSUE TITLE
Android phone, web meter

### ISSUE THREAD

**Issue by Lang-EVO** [zegreatclan/SimHub#306]
Log in to 192.168.0.x with Android mobile browser. 8888 can't use webpages normally, but Apple's mobile phone can. Is there any way to solve it?

**Comment by zegreatclan** [comment]
Hi ! You can find the full troubleshooting guide here : https://github.com/zegreatclan/SimHub/wiki/Troubleshoot-Dashstudio-Web-access if you can connect with an iPhone it means that the server is running correctly, which is a good point, so something is wrong in network config or eventually firewall.

**Comment by zegreatclan** [comment]
Make sure to use Chrome like the troubleshooting guide suggest, stock browsers coming with Android phones are often (if not always) outdated and miss critical features to get simhub working.

**Comment by Lang-EVO** [comment]
Thanks for the reply, I try it using Google Chrome.
