### ISSUE TITLE
Visual Radar R3E

### ISSUE THREAD

**Issue by hilavoku** [zegreatclan/SimHub#307]
Hi.

I tried the Visual Radar trying to use it under RaceRoom. It seems to me that the position of the own car is not updated and seems to stuck where you start the race. The other cars are moving as they should.
I can't see any parameter to solve the problem.

**Comment by zegreatclan** [comment]
Hum, I may not have understood perfectly but actually it's normal that your own car is staying in the middle as it's a radar around you, orientation may be wrong at the beginning of the lap as it requires that your car (and opponents) moves before it can detect orientation of everyone.

**Comment by hilavoku** [comment]
Sorry. I did not made it that clear. Surely the own car stays in the middle but the widget thinks that I don't move my car. When the other cars are completing there lap I see them rushing through the screen and passing me.

**Comment by zegreatclan** [comment]
Could you give me a replay when this happens ? (using the record/replay buttons on top bar) I guess it's struggling to locate the "current player" (you), i've just tested on my end with no troubles, so i guess it could related to some specifc data.  The replay will be stored in C:\Program Files (x86)\SimHub\Replays\RRRE
Only a little minute of recording would enough.

The file may be a little big and won't fit github, you can upload it to mediafire/mega or similar services.

**Comment by hilavoku** [comment]
Thanks for the reply. I will check it again and give you a link to the replay tomorrow

**Comment by hilavoku** [comment]
So I couldn't wait and checked it again.
At the end it was my fault!
I tested the visual radar with the replay function and watched some races I did last weekend. It seems there is a difference in what information R3E is giving other apps when playing a replay or when racing live.
So I did a practice session with other AI drivers and everything works fine!

Thank you for this really great program!!!

**Comment by zegreatclan** [comment]
Cool ! Thanks for the feedback  !
