### ISSUE TITLE
System.IO.__Error.WinIOError

### ISSUE THREAD

**Issue by hieblmedia** [zegreatclan/SimHub#312]
If Debug is enabled i got this error every second.
All plugins were disabled.

```
SimHub.Logging: [2019-01-12 20:26:35,488] ERROR - First chance exception error System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) 
```

**Comment by zegreatclan** [comment]
Hi ! 

This error is a first chance exception it means that it's actually handled in code, it's catched inside code, debug mode intentionnally log these kind of error.

The log is related to shared memory reading (AC, pcars ...) , as strange as it may look it's impossible to know if the shared memory file exists, so it requires to poll it regularly. And as long as it's not available it will throw this error. I kept it intentionally in log as it notifies me that the game reader is alive and trying to connect to shared memory, which is a very important clue for troubleshooting.

Nicolas

**Comment by hieblmedia** [comment]
Ah ok.
Thanks for the explanation.

**Comment by zegreatclan** [comment]
No problems ;)
