### ISSUE TITLE
Missing data: wheel slip

### ISSUE THREAD

**Issue by BorderlineRacing** [zegreatclan/SimHub#313]
I wish to display wheel slip on my dashboard. The data is transmitted by the F1 2018 game, but not available in Simhub as a property. Is it possible to implement this?

**Comment by zegreatclan** [comment]
Hi ! In,deed it was missing, my mistake :D, it's fixed for the next version.

**Comment by zegreatclan** [comment]
Hi ! The change has been released with the 6.7.1 version yesterday :

You will new be able to get the wheel slip rawdata :
![image](https://user-images.githubusercontent.com/2207331/51111679-0c2dbe80-17fd-11e9-8aca-553778f9cdee.png)
