### ISSUE TITLE
[Question] Relays controlled by Arduino

### ISSUE THREAD

**Issue by baumwolle01** [zegreatclan/SimHub#315]
I would like to config single LED´s with the Arduino... Will it be possible? Sorry for my Bad English.

**Comment by zegreatclan** [comment]
Hi, Sadly single leds are not extensible enough, on a single arduino you would be able to run a maximum of 5 leds (by keeping a 50% power safety) which is clearly not scalable to something interresting.
On the opposite way, ws2812b or PL9823 can be expanded to any number of leds wihout having any powering issues or risks.

You can read the excellent article about arduino power risks, the chapter number 10 covers this led risk : https://www.rugged-circuits.com/10-ways-to-destroy-an-arduino/

**Comment by zegreatclan** [comment]
It is possible yes by using the custom protocol : https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support

**Comment by baumwolle01** [comment]
I can´t write the Code because i can´t Programming in the Arduino IDE

**Comment by youssefaly97** [comment]
I think you should add single LEDs, they shouldn't be hard to add in software and the hardware you'd just need a proper voltage regulator with driver chips for the LEDs, just like you added a gear indicator with a 74HC595. It just doesn't make sense to add a 74HC595 that drives 7 LEDs in a 7-segment then say only 5 LEDs can be added for power safety that's ofcourse unless you mean the power limitation of the Atmega package itself. A 74HC595 is not meant to drive LEDs but it does cause 5mm LEDs just happen to draw current in the safe operating range of its output pins. A lot of people would like to use an instument cluster with its full potential including all the lights.

On another note: the speedo, tacho, fuel, temperature and mpg gauges have pullup resistors on the instrument cluster side, althought a weak pull up but it pulls up to about 7 - 12 volts, that is far from safe to connect directly to an Arduino pin. A ULN2003 or discrete transistors should be used in between.
