### ISSUE TITLE
Connect Button Matrix and Rotary encoder - assetto corsa

### ISSUE THREAD

**Issue by EBEALIEN** [zegreatclan/SimHub#316]
Goodmorning,
I use Win 7 pro, simhub contributor, Assetto corsa and Logitech DFGT.
With **arduino nano** connect with SImHub:
15 button with matrix: 3 column and 5 row
And
2 rotary encoder with enable pullup resistor
But ... i don't mapping increse and decrese brake AND other with encoder. Button is ok, mapping keyboard, but encoder NO ... sorry help me and sorry my bad english.
Antonio - EBEALIEN

_Is possible guide to mapping encoder assetto corsa?_

**Comment by EBEALIEN** [comment]
Hi, 
i have version 6.7.0 ..... ops... i download new Update 6.7.2 and re-tested. OK.
Grazie!

**Comment by zegreatclan** [comment]
Nice ;) have fun !

**Comment by EBEALIEN** [comment]
Ok,
i upload a version 6.7.2, and do not job encoder... am i wrong.
The wiring is perfect but I do not know how to map them!
![immagine](https://user-images.githubusercontent.com/17771086/51862479-04aeff00-233f-11e9-9d16-b5cd05787f94.png)
![immagine](https://user-images.githubusercontent.com/17771086/51862498-0d9fd080-233f-11e9-9619-f773a2a4d362.png)
Forgive me but I do not know how to map them,
are detected but as the key that I must assign,
any one is all right, or not?
or do you need a sequence to emulate the encoder of the DFGT?
Grazie
Antonio

**Comment by zegreatclan** [comment]
You have to set it as secondary controls as it's simply emulating keyboard, you can use any free keys you may want, it does not matter much. : 
![image](https://user-images.githubusercontent.com/2207331/51863262-daf6d780-2340-11e9-9d28-276b185f2a60.png)


Also make sure to enable "combine with keyboard input" to get it working properly in game :
![image](https://user-images.githubusercontent.com/2207331/51863354-12fe1a80-2341-11e9-917c-7fd2b7d1891e.png)

I've just tested with AC it seems that the press goes too fast for this game, launcher catches the press with no trouble but in game it's a little random, I've made the press/release delay longer and it works much better with AC,  here a link with the change : 
 ttp://www.simhubdash.com/unofficial/HubPackage.6.07.2_encodersdelay.zip

**Comment by EBEALIEN** [comment]
Incredible, in 10 minutes you have done an update!
Fantastic! Perfect! I understand little about electronics, but I've made everything work perfectly, perfect!
Mine was a test on a prototype, I proceed with the realization. It will have SimHub brand! This software is on another planet!
You are a great professional!

**Resolved and very happy!** EBEALIEN Antonio

**Comment by axeldor** [comment]
HI, I have a similar setup, everything wired the same way (just that I have 6 buttons that work perfect) but my rotary encoders are not working at all.

**Comment by Fujiwaraeffect** [comment]
Hello! I also couldn't get it to detect cw / ccw or push, although it is well wired and the pulse is reflected on the board

**Comment by Fujiwaraeffect** [comment]
I answer myself, I had the box unchecked "read buttons" (in general arduino settings)

**Comment by EBEALIEN** [comment]
Forgive me Wotever, and I hope you are well!
I'm starting again the realization of the new steering wheel, tested but never fully assembled. Now after a format of my pc, I would like to find the configuration made above of my "KEY", which is the folder path where to find it ??? I installed several times and spread simhub on each disk ....
Thanks - _At the end of the project, I will finally post the whole procedure for everyone!_
