### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by amro1230** [zegreatclan/SimHub#317]
Hello,
I really need help i downloaded simhub mobile display and i can not launch it on my windows i tried several versions, uninstalling and reinstaiiling, disable my antivirus, run as admin but it really doesnt wanna launch at all. Is there anyway you could help me with this.

**Comment by zegreatclan** [comment]
Hi !

Could you join me the log files if there are any ? They are available in C:\Program Files (x86)\SimHub\Logs

**Comment by amro1230** [comment]
[SimHub.log](https://github.com/zegreatclan/SimHub/files/2825303/SimHub.log)

**Comment by zegreatclan** [comment]
Hi ! Could you install all these packages :

https://www.microsoft.com/en-us/download/details.aspx?id=56116
https://www.microsoft.com/en-us/download/details.aspx?id=40784 (both x86 and x64, you don't need arm version)
https://www.microsoft.com/en-us/download/details.aspx?id=53840 (both x86 and x64, you don't need arm version)

If the installer says it's already installed ( it should be as Simhub has it embedded with the installer) hit repair to make sure it's correctly installed.

Nicolas

**Comment by amro1230** [comment]
![image](https://user-images.githubusercontent.com/47288342/52174599-ec364e80-275b-11e9-864e-e4caede72253.png)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/2825326/SimHub.log)

**Comment by amro1230** [comment]
from what i understand i have a problem in that dll file but i cant figure it out.

**Comment by zegreatclan** [comment]
Actually I think you missed the most important one, (2015 x86) 
Yes indeed when this happens it means the c++ redistribuable is not properly installed, it can sometimes happen when some software uninstallers removing critical files for instance)

I've joined you the installer for 2015 x86 :
[Microsoft Visual C++ 2015 Redistributable Update 3.zip](https://github.com/zegreatclan/SimHub/files/2825342/Microsoft.Visual.C%2B%2B.2015.Redistributable.Update.3.zip)

**Comment by zegreatclan** [comment]
I've made some additionnal search about the crashing component (cefsharp), usually installing/repairing the c++ dependencies is enough : 
https://github.com/cefsharp/CefSharp/issues/466
https://github.com/cefsharp/CefSharp/issues/850
https://github.community/t5/Project-Development-Help-and/Could-not-load-file-or-assembly-CefSharp-Core-dll-or-one-of-its/td-p/4642

I also had also some experiences in the past where repairing was enough to get cefsharp working again,  If it's not enough I would think it's corrupted deeper than a repair wouldn't catch it. Could you try an uninstall / reinstall the 2013 x86 and 2015 x86 packages ?

**Comment by amro1230** [comment]
[SimHub.log](https://github.com/zegreatclan/SimHub/files/2825816/SimHub.log)
i tried everything now and this the last log file. I kinda gave up on this problem i think the only way this might get fixed is buy reinstalling windows. I really apperciate your help with them and your time.
