### ISSUE TITLE
DK shield - Motor 3 not enabled; motor 1 not adjusted for hum (Arduino sketch)

### ISSUE THREAD

**Issue by redion1992** [zegreatclan/SimHub#318]
In the file SHShakeItDKMotorShield.h, line 37 reads as `DKMotors[3]->run(FORWARD);`, the same as line 38. It should probably read `DKMotors[**2**]->run(FORWARD);` since this motor doesn't have a line for it.

Also in this file, there are calls to trigger `setPwmFrequency()` on pins 3, 5 and 6, which affect motors 2, 3, and 4 (see https://learn.adafruit.com/adafruit-motor-shield/faq#faq-12 for this info source). To affect motor 1, the same must be applied on pin 11.

**Comment by zegreatclan** [comment]
I checked, setting the motor 3 affects the power and can't be tuned like the others i'm affraid
