### ISSUE TITLE
Problems with 74HC595

### ISSUE THREAD

**Issue by Tigrejor** [zegreatclan/SimHub#319]
I tried to make a custom gear indicator with 74HC595 but the code seems not to be working properly.
It shows a different number from expected, for example when it should show 1 it lights mid and upper left segments, when it should show 2 it's missing the upper segment, as 3 it shows a mirrored 4. I tested the connections already and all the segments light up.

**Comment by zegreatclan** [comment]
Hi ! It looks like you are not using the same segment ordering, sincce you have tested each segment with success
 you can change the ordering in the code :

In C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2\DisplayClientV2.ino
Line 593 you will find the "number to segments" mappings and be able to customize it to fit your actual wiring :

![image](https://user-images.githubusercontent.com/2207331/52302753-6a7a3700-298e-11e9-8446-2e54626f29ac.png)

**Comment by Tigrejor** [comment]
Thanks for your response. In case I got a different segment ordering, is there any documentation related to the usage of the 74HC595? I couldn't find any and had to use a generic wiring from other tutorials.
Also, what is the order of characters in that line?

**Comment by zegreatclan** [comment]
Actually the wiring is probably correct, but as you can wire each digit in any order from the chip, it's just the ordering which differs and makes it appear not correct (as you said you find the correct number of segments, they are just at the wrong place) , 

Along the sketch you will find the wiring, it has been made a long time ago by a early simhub user, I never had a chance to test it myself, but it should work  :
74HC595 EXTERNAL GEAR INDICATOR SCHEMATICS.docx
inside C:\Program Files (x86)\SimHub\_Addons\Arduino\DisplayClientV2

The numbers in the sketch are in the following order 0 ,1, 2 ,3 ....

**Comment by Tigrejor** [comment]
I checked my wiring against the one in the doc you said and you were right, the order is not correct. What I noticed from looking into that wiring scheme and an output table from the internet, is that the wiring on the schematic included and therefore on the code, is turned around, as in the table shows 00111111 for the 0 and in the code it is put as 11111100.
Again, thanks for such fast response, and you can consider this as solved from my end.

**Comment by zegreatclan** [comment]
Perfect ! Have fun !

**Comment by Tigrejor** [comment]
I tested again with the modified code and every number works as expected, except for the 0 which I don't know why it shows a 5 with the dot light up instead of the upper segment, but still better than not working at all ^-^.

**Comment by zegreatclan** [comment]
Actually 0 is the neutral digit (N), three lines later, it's the one you need to modify.

**Comment by Tigrejor** [comment]
Woops didn't notice the line, thank you very much!!!
