### ISSUE TITLE
Launch Dashboard in browser automatically fullscreen?

### ISSUE THREAD

**Issue by Rookie0ne** [zegreatclan/SimHub#324]
Currently when opening one of the Dashboards (e.g. SimHub Leaderboard) in Chrome via http://192.168.1.21:8888/Dash#SimHub%20Leaderboard it runs inside the Chrome tab and shows me on top the overlay that offers me "Fullscreen" "Reload" etc. If I press "Fullscreen" here it correctly goes into fullscreen mode.
Is there a possibility (e.g. via URL parameter) to launch immediately into fullscreen mode and not having to show this command overlay anymore?

**Comment by zegreatclan** [comment]
hi ! Sadly it's not possible, fullscreen can be only initiated by a user input (click swipe ...) It's a security measure from the browser itself.
