### ISSUE TITLE
Alternative download location?

### ISSUE THREAD

**Issue by yibbayabbba** [zegreatclan/SimHub#326]
After i called a racedepartment mod out for being biased and censoring comments he decided to ban me, i now can't download any updates for sim hub, would an alternative download location be possible?

**Comment by zegreatclan** [comment]
Hi ! Currently there is no alternative mirror, 
However,I've uploaded you the latest version due to be published this evening (it adds DR 2.0 compatibility) : 
http://www.simhubdash.com/downloads/HubPackage.6.07.5b.zip

**Comment by yibbayabbba** [comment]
hi, thank you very much, will there be an alternative location in future
maybe?

**Comment by zegreatclan** [comment]
I'm affraid the Racedepartment mod rules doesn't allows it, and since I do most of the support here going out of racedept would be a big issue for me.

**Comment by yibbayabbba** [comment]
racedepartment won't allow you to upload the mod elsewhere? wow didn't know
that, sounds like a bit of a dick move from them, no worries, i'll find a
way to get updates, great piece of software by the way
