### ISSUE TITLE
Need help with bass shakers configuration (wiring)

### ISSUE THREAD

**Issue by Marche777** [zegreatclan/SimHub#327]
Hi, I'm Andrea.

I have this soundcard: [link](https://www.amazon.it/gp/product/B00EO6X4XG/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)

Four of these bass shakers: [here](https://www.daytonaudio.com/index.php/bst-1-high-power-pro-tactile-bass-shaker-50-watts.html)

This amplifier: [here](https://www.amazon.com/SMSL-SA-98E-Digital-Amplifier-Adapter/dp/B00NBGECXG)

This cable: [here](https://www.amazon.it/UGREEN-10584-Audio-Adattatore-3-5mm/dp/B00LM2Y2U4)

My question is: **Can i run Shakelt bass shakers in 4 channels (4 outputs) mode?
How do i have to wire my soundcard to my amp? And which settings should i choose inside the software?**

I've already read this [guide](https://github.com/zegreatclan/SimHub/wiki/Shake-It-for-bass-shakers) , but i'm not sure of these steps.

Sorry it's my first experience with this type of stuff.

Many thanks,

Andrea

**Comment by zegreatclan** [comment]
Hi ! 
Your amplifier has only two channels, so you won't be able to drive your shakers in 4channels mode but only in two channels mode, but you can still drive all of them (but not separately)

So basically you will need to wire using the cable you have bought from the sound card (usually green plug) to the amplifier "audio in",

Finally for the amplifier to shakers wiring you have the wiring described on dayton audio manual link you have sent : 
https://www.daytonaudio.com/index.php/bst-1-high-power-pro-tactile-bass-shaker-50-watts.html

I've tried to make the dayton audio suggested wiring more clear for two channels : 
![image](https://user-images.githubusercontent.com/2207331/53243107-2170f500-36a7-11e9-8283-2145562d53c9.png)

If you want 4 separate channels you will need an additional amplifier

**Comment by Marche777** [comment]
Yes it helps a lot. 

So basically i do have to wire both right shakers to the right channel and both the left shakers to the left channel of my amp. 

And later on the software part other then choose 2 channel mode in simhub, do i have to change some settings inside windows panel? Like in realtek (stereo, quadriphonic, 5.1, ecc..)?

And then...
if i decide to run all of them separately i must have two aplifiers with two channel both. In this case how should i wire them? (amps to che soundcard and shakers to the amps). 

Ones i'm sure to have understood i may buy another amp. 

Thank you zegreatclan!

Andrea

**Comment by zegreatclan** [comment]
In two channels mode the current sound card configuration would not have much influence as there is always at least two channels active. In 4 channels mode you will have to ensure to configure it in quadriphonic (4channels)

For 4 channels, you will simply have to add another "jack to rca" cable plugged to the "rear" output of the sound car going to the second amplifier "audio in" (sound card plug color may vary so you will have to check your sound card manual or do "trial and error" method)
For the shakers it will be more simple as it will be one shaker per amplifier output so it will be simply + to + and  - to - for each output of each amplifier (like you would do with any speakers). 

I've checked  your amplifier specs, it's rated for 160w@4ohms so it should not be an issue at all in "one shaker per output" configuration (good choice by the way, it seems to be really good amplifier for the price).

**Comment by Marche777** [comment]
Ok, thank you Zegreatclan

Now it's all clear. Next week i'll try first how's the feeling with just 1 amp. 
There's some place here where i can found a good profile for shakelt? I would like to start doing my job with a good base. 

Thank you again

**Comment by zegreatclan** [comment]
I've bundled Shake with preloaded default profiles for almost all modern games,
you can see how the effects tuning works here : 
https://github.com/zegreatclan/SimHub/wiki/Arduino-Shake-It#shakeit-configuation

There is not much profiles shared as sharing them is kind of meaning less, let me explain, the feeling will change a lot depending of the amplifier, the shakers, the mounting, your personnal taste, the game .... so something which will be good for a specific setup has almost no chance to feel the same on another setup.

**Comment by Marche777** [comment]
Ok, thank you for the hyper fast support!
