### ISSUE TITLE
My WS2812 dot matrix display is not working

### ISSUE THREAD

**Issue by 1499263389** [zegreatclan/SimHub#328]
Before the software was connected to WS2812 dot matrix screen, there was a digital display error. Arduino-WS2812 dot matrix display is abnormal, the gear is wrong.My development board is Arduino UNO, data can be burned in, but the digital display is wrong, replaced by a UNO development board or wrong, I think it should be software burning program scrambling.

**Comment by zegreatclan** [comment]
Hi ! Do you have a link to your matrix ? 
I'm affraid WS2812B Support was experiental and it had never been released officially, I plan to replace It with a better option (colorduino like) which has a better color diffusing for the purpose.
