### ISSUE TITLE
Wrong fonts on iOS

### ISSUE THREAD

**Issue by djmartinvega** [zegreatclan/SimHub#332]
Hello 
I have an issue on my iOS browser. Some dashes fonts are not displayed on safari. The proper fonts are replaced by default font. For example in Motec dash, DS-digital font is replaced by times default font on safari. 
In window mode on PC screen font are displayed corectly and everything is fine. 
I have installed all reqired fonts o windows.

**Comment by zegreatclan** [comment]
Hi ! 

Could you specify me the IOS version, and the exact dash used ? (download link).
 Some older versions of IOS versions such as ios 8 and earlier if i'm not wrong have bad support of custom fonts. 

Concerning adding new fonts, make sure to restart simhub after having the fonts installed , and properly refresh the  browser, if it's not enough you can eventually clear the browser cache : https://support.apple.com/en-us/HT201265

I know that IOS may reject some fonts considered as "unsafe" I'm not sure if it's the case of the DS-Digital font.

Let me know if it helped,

Nicolas

**Comment by djmartinvega** [comment]
Hi
iOS 11 (today I will try to update to 12)
SimHub version 6.7.5 downloaded from racedepartment. Motec dash was included in SimHub? or downloaded also from RD - I can't remember. 
I did restart SimHub and browser after font installed. 
I will try to clear browser cash today afternoon when I get back home. 

Thank you for help.
Marcin

**Comment by djmartinvega** [comment]
Unfortunately after updating a iOS to v12 and clearing the cache the problem still occure. Still wrong fonts on my phone:(

**Comment by zegreatclan** [comment]
could you tell me which dash exactly ? I've made some tests with IOS and I could not find any missing fonts on the standard dash, I would like to check the one you are using particularly.

**Comment by djmartinvega** [comment]
![D206B56A-BFD9-4B02-B486-208E277162EA](https://user-images.githubusercontent.com/48543958/54383411-4cd97500-4692-11e9-88ae-7ac44564a62d.png)
The blue obe from this package: 
https://www.racedepartment.com/downloads/dashboard-creations-for-simhub.15590/

**Comment by zegreatclan** [comment]
Thanks ! I will take a look !

**Comment by zegreatclan** [comment]
I've tested it with no troubles, could it be possible that all the versions of the fonts are not installed ? (it requires 4 of them) 

Here a zip with all of them : 
[Fonts.zip](https://github.com/zegreatclan/SimHub/files/2968076/Fonts.zip)

If it does not solves it could you send me the following files :
C:\Program Files (x86)\SimHub\Web\FontFaces.css (this is the file which gives the font path based on your system installed fonts)
And the log files available here : C:\Program Files (x86)\SimHub\Logs (if somehow the file is not regenerated it would be visible here.)

**Comment by djmartinvega** [comment]
Apart of this issue I’m really enjoy the app! It’s brilliant! 
Also I’m happy with my dash project for my old iphone 😉
![ECC5194B-1B48-47C4-B29F-3B221BEF6190](https://user-images.githubusercontent.com/48543958/54384609-ebff6c00-4694-11e9-87f8-2f8abb60b36b.jpeg)

**Comment by zegreatclan** [comment]
Nice !

**Comment by djmartinvega** [comment]
I have already installed all 4 included fonts without reaults. I will send mentioned files tomorrow. 
Thanks!

**Comment by djmartinvega** [comment]
Hi!

Here you can find my files. I attached the picture how it looks like on my mobile.
https://drive.google.com/open?id=1p1dnUG-NNS77U0jEBzAVuSQ-q9nPwhsi
![54258285_364561781061947_1732982328562548736_n](https://user-images.githubusercontent.com/48543958/54441226-98485d80-473c-11e9-8dc6-7316f51012d4.jpg)

**Comment by zegreatclan** [comment]
Thanks, i think I've understood why it does not works, you have a few fonts with a few special characters (mostly quotes, which is pretty uncommon in font names) I need to do some tests when I will be at home, but I guess it breaks the css file. I need to add some escaping

These are the fonts I've seen : 
"a bug's life - debugged"
"a bug's life"
and "That's Font Folks!"

**Comment by djmartinvega** [comment]
Thanks! In meantine I will try to delete the fonts with special characters from windows directory.

**Comment by djmartinvega** [comment]
I have deleted all not standard fonts from windows and delte fontfaces.css file. But it didn’t work. Still wrong font on mobile

**Comment by djmartinvega** [comment]
Hi Nicolas

It looks that I have solved the problem. I don't know exactly how, but I did a few steps:
1. I have deleted all non standard windows font
2. Some folders with Dashes had compressed properties, I have turn off compresion in folder properties
3. I have installed all fonts from dashes folders 
4. I started the FontReg.exe from simhub FontReg folder.

Now everything woks good :)

**Comment by zegreatclan** [comment]
Ah cool ! I've been experimenting with your fontface file and I found some additional fonts causing troubles, I've covered all the cases automatically for the next version, I've also enforced browser cache refresh so it always get the latest definition. It should cover all the cases(this 1800 fonts file was a good crash test :D )

**Comment by djmartinvega** [comment]
Thank you for help with this issue :) 
SimHub is really brilliant tool! Now I'm jumping to the car ;) 
Have a nice weekend!
