### ISSUE TITLE
Add interface to control Simhub via web requests

### ISSUE THREAD

**Issue by Baptiewright** [zegreatclan/SimHub#335]
Please add the ability to send requests to the Simhub web interface in order to trigger actions like switching pages etc.

**Comment by zegreatclan** [comment]
Hi ! 
for the next release i've added this api, simply replace "hello" with your input name and it will be possible to map this "input" to most simhub controls
http://192.168.0.15:8888/api/triggerinput/hello

**Comment by Baptiewright** [comment]
this is excellent, when you say input you mean like "screen1_button7" or something?  I don't suppose you could add on "/api/listinputs" that just returns a plain text list of all configured input names?  Then I could build a plugin for Stream Deck that lets the user pick from a dropdown list and have it would mak a button that triggers that input.  Thanks for your hard work on Simhub!

**Comment by zegreatclan** [comment]
you can give it the name you want it will create an input on the fly using the name you gave :
![image](https://user-images.githubusercontent.com/2207331/55583278-c4467580-5721-11e9-8685-c3e024c0a046.png)

**Comment by Baptiewright** [comment]
ok then calling the same URL again (with the new input name) triggers the input?

**Comment by zegreatclan** [comment]
Yep ! Exactly !
