### ISSUE TITLE
LED module bug in iRacing

### ISSUE THREAD

**Issue by SalmonMan118** [zegreatclan/SimHub#336]
I've been using RGB LED module for some times mostly with rFactor2 and Assetto Corsa. Recently I started iRacing and came across the LED doing something weird. Basically it suddenly lights up VERY brightly. It seems like there is no pattern, sometimes it's the far left one, sometimes it's the fourth from the left. I use 8-Bit WS2812 with Arduino Nano. LEDs are too bright so I set it to 2% of brightness. 
 I've carefully looked at my LED template but didn't find any apart from RPM gauge I designed. And this only happed for iRacing.

**Comment by zegreatclan** [comment]
Hi ! 
Considering the behaviour this has good chances to be related to a weak solder making the signal unstable or a defective strand (but this is more rare), You can find an excellent guide from adafruit here about good soldering as it's most of the time the main issue for such behaviour :https://github.com/zegreatclan/SimHub/wiki/Arduino--Setup#soldering, I suggest to start here before all as it's the most probable hypothesis.

This could be also bound to some parasites triggered by the wheel (if the ffb is configured stronger for instance o ircing), I would suggest to avoid usb hub if you use one or change usb port to see if it helps.

You can check the actual colours sent using the "led emulator",this is plugged as close as possible from the actual led data sent to the arduino so it will show you the actual led colours, so you can check if it's software related : 
![image](https://user-images.githubusercontent.com/2207331/55245229-06b01400-5243-11e9-9484-4629e0290488.png)

Let me know if it helped, 

Nicolas

**Comment by SalmonMan118** [comment]
Hi thanks very much for quick yet detailed answer! I’ll give them a try tomorrow or so.
