### ISSUE TITLE
Bug Delta in raceroom

### ISSUE THREAD

**Issue by L3aARG** [zegreatclan/SimHub#337]
Hi! I have been using SimHub since version 6.7.5 full in RaceRoom. My most used overlay is the AT DeltaBest and it seems not to work fine the most of the times. Both times gets out of synch as shown on the image below. is there any additional configuration to avoid this situation? Thanks in advance.
![Sin título-1](https://user-images.githubusercontent.com/49171693/55361751-8beb3100-54ae-11e9-9c0c-4a57e648a200.jpg)

**Comment by pdoggyster** [comment]
I have same problem.

**Comment by pdoggyster** [comment]
Could you give me some information when will this patch be released? Becasue it's still there.
