### ISSUE TITLE
The new raceroom update broken the simhub

### ISSUE THREAD

**Issue by pdoggyster** [zegreatclan/SimHub#339]
https://forum.sector3studios.com/index.php?threads/the-march-2019-developer-notes.12862/

6. Shared memory API - Massive update.

As I've touched somewhere on the forum, our next update will break 3rd party applications that use our shared memory block.

If you are a developer of such applications, please have a look at the attachment " r3e_sharedmem_preview_march2019.zip " to get an early look at the changes.

The goal of this update is to expose all the possible telemetry you can dream of, and extend the possibilities for apps and overlays.

**Comment by zegreatclan** [comment]
Hi ! The release is under testing right now and should come under one hour ;) time to make sure everything is ok ;)

**Comment by zegreatclan** [comment]
The update have been released ;) https://www.racedepartment.com/downloads/simhub-diy-sim-racing-dash.10252/update?update=46566

Have fun !
Nicolas

**Comment by pdoggyster** [comment]
It's working fine, Thanks! Awesome works!
