### ISSUE TITLE
7 segment display issue

### ISSUE THREAD

**Issue by THATSNUTS** [zegreatclan/SimHub#340]
Hi Z 

Having a small issues with 7 segment display running through 595 chip gears all change and works fine however when rev reaches max gear indication changes to a zero and flickers on every gear does not seem to be any code in the arduino sketch or simhub software settings to explain why this would be happening it's like it's picking up rev limit light. Any ideas. 
2. This arduino is also running two wb2812b led sticks which also have an odd error when revs slowly increase some of the leds higher up randomly come on and flicker even though the simhub software should be not allowing them to come on at all. I've tried this with individual led modules and they work fine but the 8 led stick is not working as it should. Any ideas would be appreciated.

**Comment by zegreatclan** [comment]
Hi ! Concerning the 595 I will take a look, concerning the LEDs it looks like some bad or weak solder. Ws2812b LEDs are really sensitive to parasites which can be caused to weak soldering for instance, it's the most common issue with ws2812b LEDs
You can read a very good guide made by adafruit about good solders here https://github.com/zegreatclan/SimHub/wiki/Arduino--Setup#soldering. It could be also a defective strip but it's much more rare. The sketch code is made to ensure to reject any communication error, missing data even at high speed so there is only a very little chance that it comes from communication. You can see the LEDs content generated by simhub by using the "emulator" button on top of the LEDs layouts list

**Comment by THATSNUTS** [comment]
I thought about that however I do soldier alot and the joints are perfect but and a big but I'm currently using a breadboard for final connection to arduino I'll try soldiering this joint tomorrow. Have tried different modules same result so this may be the problem. Will also try new nano v3 currently trying micro.

**Comment by THATSNUTS** [comment]
Update, 7 segment issue partially solved simulator sends signal at rev limit to flash between current gear selection and no gear and I had no gear defined as a zero after making all segments low gear indicator now just flashes on and off. I'd like to turn the function off but it's initiated from the sim not simhub so each sim will be different. Issue here solved.
Issue two still no idea all fully soldiered in to new nano board and joints are spot on still getting random leds flashing very frustrating but will just have to wait until new ones arrive. Other individual 10mm round units I have work fine I've strung 10 of them together and they work well so I'm picking these cheap ones are rubbish.

**Comment by THATSNUTS** [comment]
Issue two partially resolved now after purchasing an official arduino module and sticking that in the mix it works. Still no idea why the others don't work tried 4 different modules and when paired together they do so random stuff. Clearly not all wb2812 modules are the same. If yours is the same cheap version you'll have the first couple leds come up fine then random ones come on further up the line as rev increase flickering and going on and off. Official arduino modules are the same but have code xc4380 available from electronics stores but $9 each, but I can state they are compatible with your code and work well. Would love to have somewhere all available formulas for led indication are like all flags pit limiter all warning lights. Understanding not all sims output this data but somewhere they're all listed would be good there is a link I found on here with some but they're randomly sprayed throughout the posts. I'm really after pit limiter not in pit so leds flash if you push pit limiter outside pit lane. Case closed
