### ISSUE TITLE
high cpu usage from version 6.7.4

### ISSUE THREAD

**Issue by nagler2** [zegreatclan/SimHub#342]
I use SimHub for shakelt and all versions till 6.7.3 were just fine. But from v. 6.7.4 cpu usage is crazy and shakelt works not correct. I play always in VR. Now I have to use version 6.7.3, but some updates are important and I would like to know, what the problem is. Thanks!

**Comment by zegreatclan** [comment]
Hi ! Could you join the log files after using the latest version ? I did not had other reports so I guess it's somehow related to an error, the log files will give some clues.
Log files are stored inside the log folder inside the simhub install directory.

**Comment by nagler2** [comment]
Hi! Simhub-2.log is from last version. The another one is from 6.7.3. 

[2019-04-19 19:11:36,748] INFO - Fuel at the beginning of the lap : 99.76
[2019-04-19 19:11:36,899] INFO - New non valid lap detected

Thank you very much for your help and time!

Sent from Mail for Windows 10

**Comment by zegreatclan** [comment]
Hi ! Could you put the log files directly on github ? When replying using mail the attachements are not available.

Nicolas

**Comment by nagler2** [comment]
[SimHub (2).log](https://github.com/zegreatclan/SimHub/files/3104744/SimHub.2.log)
[SimHub1.log](https://github.com/zegreatclan/SimHub/files/3104745/SimHub1.log)

**Comment by zegreatclan** [comment]
hi ! From what I see you have an udp forwarding active on the same udp port which will mess with data, from 6.7.4 this feature has been improved and it's probably why this bad setting has an influence now : 
Make sure to disable it or to redirect it to another port to avoid this
![image](https://user-images.githubusercontent.com/2207331/56817635-381dfe80-6846-11e9-824a-f6c45385e392.png)

**Comment by nagler2** [comment]
Hi! Thank you very much, that solved the problem. Would be nice to have a button to reset all settings in SIMHUB, so every noob could first try this option)
Thank you again!

Sent from Mail for Windows 10

**Comment by zegreatclan** [comment]
Hi sadly there are many settings files and resetting it automatically will be almost impossible, 
however the process to do a full reset is described here : https://github.com/zegreatclan/SimHub/wiki/SimHub-Troubleshootings
