### ISSUE TITLE
probleme ventillateurs qui se coupe par intermittences

### ISSUE THREAD

**Issue by JeromeRnd** [zegreatclan/SimHub#343]
Salut j'ai des problèmes de coupures par intermittences des ventilos,  cela arrive sur plusieurs circuits, et voitures

**Comment by JeromeRnd** [comment]
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103675/SimHub.log)

**Comment by JeromeRnd** [comment]
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103680/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103684/SimHub.log)

**Comment by JeromeRnd** [comment]
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103686/SimHub.log)

**Comment by JeromeRnd** [comment]
Je ne sais pas si cela vient du coup d'un problème matériel

**Comment by zegreatclan** [comment]
Je suis sur mon téléphone j'ai regardé comme j'ai pu et tout a l'air propre dans tous les logs que j'ai pu ouvrir, aucune déconnexion du jeu ou de l 'arduino ça ressemble a une coupure thermique du coup (en général ça dure une seconde ou quelque chose de proche.) Quelle puissance font les ventilateurs ? Quand l'arduino se déconnecte côté simhub ça va durer 3s a 4s mais je n'ai pas vu ce type de déco dans les logs

**Comment by zegreatclan** [comment]
Edit : ce genre de coupures peuvent aussi se produire côté bloc d'alimentation si il est un peu trop limite en terme de puissance.

**Comment by JeromeRnd** [comment]
Merci pour ton retour, tu as été vite ! Je n'ai pas mis tous les logs je vais poster les autres, les 2 ventillateurs font 1.52A, 18,24w et 12volts, et l'alim fait output : 12v 5A
La déconnexion dure à peine 1 seconde.
Cela pourrait donc venir du bloc alim...
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103739/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103740/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103743/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103746/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103749/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103753/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103754/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103756/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103758/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103759/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103760/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103761/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103762/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103763/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103764/SimHub.log)
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3103765/SimHub.log)

**Comment by zegreatclan** [comment]
Techniquement ça doit tenir, pour alléger un peu la carte je mettrai un ventilateur en sortie #3 car il y a une puce pour 2 sorties (1 et 2 puis 3 et 4) si c'est une coupure thermique ça répartira la charge sur les deux puces.

**Comment by JeromeRnd** [comment]
Super vais tester direct ;)

**Comment by JeromeRnd** [comment]
Je crois que tu as résolu mon problème !!! J'ai fait comme tu m'as indiqué et plus de micro coupures ! Merci encore pour le temps accordé et le boulot réalisé ;)

**Comment by zegreatclan** [comment]
Parfait !

<Début de mauvais jeu de mot> Bon vent ;) <Fin de mauvais jeu de mot>
