### ISSUE TITLE
android apk

### ISSUE THREAD

**Issue by buellers** [zegreatclan/SimHub#344]
using android apk, cant type in : (colon) so cant connect, this happens even if copy and paste the working ip from chrome, : colon does not work.
thanks

**Comment by zegreatclan** [comment]
Hi ! You just need to type the IP (ie 192.168.0.10), the android app only supports the default port 8888 for now)

**Comment by buellers** [comment]
Thanks, I didn't realise
________________________________

**Comment by zegreatclan** [comment]
No problems ;) Have fun !
