### ISSUE TITLE
simhub crashing

### ISSUE THREAD

**Issue by amro1230** [zegreatclan/SimHub#350]
simhub keeps crashing from time to time whenever using simhub studio to design !
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3243530/SimHub.log)

**Comment by zegreatclan** [comment]
Hi ! 
Could you join the log file after the crash, this one is the latest but has not catched any "crash",
You can find also all the past log files in the same folder,

Nicolas

**Comment by zegreatclan** [comment]
Hi ! I've got another report with the appropriate log files, and i've been able to locate the issue, it will be fixed with the next version.
