### ISSUE TITLE
Nextion Setup -> nothing selectable under "Use Editor"

### ISSUE THREAD

**Issue by dpmalito** [zegreatclan/SimHub#351]
I follow instructions with the editor to make the nextion 59xx template and when i get back to simuhub there is never anything to select under "Use Editor" pulldown.

i have copied the files into the main dir and uploaded the template to my nextion

any ideas? thanks. Yes, I restarted SImhub twice.

**Comment by zegreatclan** [comment]
Hi !

Assuming you are using the latest simhub version (V6.7.8), all those templates have been migrated to the "editor mode" : https://github.com/zegreatclan/SimHub/wiki/Nextion-Display---Installing-an-'editor'-template
You will have 3 files to copy into C:\Program Files (x86)\SimHub\NextionTemplate
![image](https://user-images.githubusercontent.com/2207331/58822721-732b0300-8638-11e9-8429-6ec0ecb4cf30.png)

When done there just select the values like this :
![image](https://user-images.githubusercontent.com/2207331/58822900-d0bf4f80-8638-11e9-9005-0460ec916a4a.png)

Let me know if it helped,

Sincerly,
Nicolas

**Comment by dpmalito** [comment]
It worked !!! Thanks so much! 

Sincerely,

Daniel P. Malito
Author, columnist, raconteur

Huffington Post
https://m.huffpost.com/us/author/daniel-p-malito

Chronic Briefs Podcast
https://itunes.apple.com/us/podcast/chronic-briefs/id1111862614?mt=2

http://www.danielpmalito.com, Daniel P. Malito on Facebook, @danielpmalito on Twitter

**Comment by zegreatclan** [comment]
Perfect ! Have fun !
