### ISSUE TITLE
Special characters issue

### ISSUE THREAD

**Issue by Romainrob** [zegreatclan/SimHub#353]
Hi again!
I noticed that special characters in the drivers names don't display properly.
It looks like it could be an iRacing thing again. Hopefully it can be fixed.
Thanks!

![image](https://user-images.githubusercontent.com/50543913/58921287-37766300-8736-11e9-87cd-7b96db2f2f0a.png)

**Comment by zegreatclan** [comment]
Hi ! Indeed found the issue, the hardest part was to find an appropriate session for testing :D

**Comment by Romainrob** [comment]
Hi! I'll share you a replay on discord!

**Comment by zegreatclan** [comment]
Fix released with 6.8.0 ;)
