### ISSUE TITLE
Dashstudio functions list - drivergaptoplayer

### ISSUE THREAD

**Issue by Romainrob** [zegreatclan/SimHub#354]
Bonjour,
It looks like there has been a mixup with the drivergaptoplayer and drivergaptoleader in Dashstudio functions list.

![image](https://user-images.githubusercontent.com/50543913/58963701-ee61f580-87ad-11e9-843c-6b0e4fef1816.png)

Also clicking on the second drivergaptoleader(raceposition) does insert drivergaptoleader, not drivergaptoplayer.

**Comment by zegreatclan** [comment]
Well seen ! It's fixed for next version ! 
Thnaks again for your report !

**Comment by Romainrob** [comment]
Thank you for your amazing work!

**Comment by zegreatclan** [comment]
Fix released with 6.8.0 ;)
