### ISSUE TITLE
combining two nextion templates

### ISSUE THREAD

**Issue by dpmalito** [zegreatclan/SimHub#355]
i was trying to paste a page into an existing nextion template using the nextion editor import/export page function since there isnt much selection of nextion templates but it never seems to work right.  is it possible or should i just give up?  if i can, whats the trick?  thx

**Comment by zegreatclan** [comment]
Hi ! Sadly this will often leads into conflits between the templates and names, however after combining it, you must make sure to regenerate the structure file, then review the mapping in the editor, you can take a look at the general template creation process here : https://github.com/zegreatclan/SimHub/wiki/Nextion-Display---Template-creation-using-mapping-editor

**Comment by dpmalito** [comment]
Thanks for the quick response... i had one other question.. in Assetto Corsa Competitizone only a few of the telemetry works. Is that me doing something wrong or is ACC not fully supported yet?

Thanks.

Sincerely,

Daniel P. Malito
Author, columnist, raconteur

Huffington Post
https://m.huffpost.com/us/author/daniel-p-malito

Chronic Briefs Podcast
https://itunes.apple.com/us/podcast/chronic-briefs/id1111862614

**Comment by zegreatclan** [comment]
No no, you are not doing something wrong, the game developers haven't invested time into getting proper telemetry for the official release, let's hope it will come really soon, as soon as they will fix that, I will integrate it.

**Comment by dpmalito** [comment]
Wow you’d think they would have for the official release.  Sheesh. 

Thanks again for your help! I looked at that page I may email you with a question or two.  If you don’t mind.  🙏 thanks

Sincerely,

Daniel P. Malito
Author, columnist, raconteur

Huffington Post
https://m.huffpost.com/us/author/daniel-p-malito

Chronic Briefs Podcast
https://itunes.apple.com/us/podcast/chronic-briefs/id1111862614?mt=2

http://www.danielpmalito.com, Daniel P. Malito on Facebook, @danielpmalito on Twitter
