### ISSUE TITLE
Dashstudio wrapping/centering in HTML mode

### ISSUE THREAD

**Issue by Romainrob** [zegreatclan/SimHub#361]
Bonjour,
It looks like text wrapping and text centering don't play nice in HTLM mode:
Desktop mode : 
![image](https://user-images.githubusercontent.com/50543913/60057863-630dbd00-96e6-11e9-96e0-51e6e9b0981b.png)
HTML mode : 
![image](https://user-images.githubusercontent.com/50543913/60057888-791b7d80-96e6-11e9-834d-c42a37ec5f34.png)
Using the Sergoe UI font.

**Comment by zegreatclan** [comment]
Thanks for the report ! it's fixed !

**Comment by Romainrob** [comment]
Awesome! Thank you!

**Comment by zegreatclan** [comment]
Fix released with simhub 6.8.2 ;)
