### ISSUE TITLE
Conection Lost Monitor ACC

### ISSUE THREAD

**Issue by goodBEER74** [zegreatclan/SimHub#370]
I use the Dashboard (https://www.racedepartment.com/downloads/simhub-custom-dashboards.20460/) for ACC. Unfortunately I have connection interruptions again and again. But I don't know why. Can you help me? I use Simhub via a 7" monitor, connected with HDMI cable directly to the graphics card.

I keep losing touch with Simhub. The dashboard loses the connection and is stuck (still picture). After some time Simhub connects again and the dashboard works again and then again shortly later still picture.

[Logs.zip](https://github.com/zegreatclan/SimHub/files/3363522/Logs.zip)

**Comment by goodBEER74** [comment]
Problem still exists. Do you already have a solution?

**Comment by zegreatclan** [comment]
Hi ! I took a look at the logs but sadly I could not find any recurring pattern, it seems to freeze anywhere. At first sight I would think about running out of ressources (maybe GPU ?) Could you try to enable high priority in settings, and check your GPU / CPU load to ensure you are not running at 100% ? ACC is quite demanding compared to most games.

On another hand a simple test would be to disable each plugins (in settings) one by one to see if somehow one is not guilty. The logs does not shows any particular overconsumption, but it's worth a try.

**Comment by goodBEER74** [comment]
my CPU ingame is about 40% and the GPU is 99%. Do the disconects come from too high a GPU load?

**Comment by zegreatclan** [comment]
Ah indeed that explains it, if you run at 100% something has to be "dropped" and in this case it will be simhub, since most of the time focused application will get priority. It  explains those random "freeze" I see in the logs happening pretty much anywhere since the rendering engine will get stuck until having power for rendering. From experience a full GPU is really unforgiving compared to a full cpu

**Comment by goodBEER74** [comment]
Problem solved. I have turned on the Higher process priority in the settings. Now there are no more disconects.

**Comment by goodBEER74** [comment]
Post can be closed
