### ISSUE TITLE
2nd PC

### ISSUE THREAD

**Issue by ilimo** [zegreatclan/SimHub#371]
Hello...
I am running SimHub on a 2nd PC which is connected via Wifi to the network.
My 1st PC is hardwired to the same network and it's where the game starts up.
The 2nd PC with SimHub isn't showing Game Connected and the dashboard doesn't start up.
How can I get the 2nd PC with SimHUB to detect the 1st PC started the game and run the dashboard from it?

**Comment by zegreatclan** [comment]
Hi ! Simhub is mostly made to run on the game computer, you won't get remote game connection, 

However dashstudio allows you to show dashboards using web access, simply open a browser on the second computer and use the same address as mobile access : 
![image](https://user-images.githubusercontent.com/2207331/60758128-e9de6600-a013-11e9-8c26-86115f398dd9.png)

Nicolas
