### ISSUE TITLE
System.OutOfMemoryException - Crashes

### ISSUE THREAD

**Issue by Romainrob** [zegreatclan/SimHub#373]
Hi!
Since the 6.8.1 I'm having some "System.OutOfMemoryException errors". Then SimHub hangs and crashes. I happened 3 times in 2 days now while being on the ShakeIt effects screen. The last one happened as I was AFK and no game was running.
Someone reported something similar on Discord so it may not be my custom stuff causing it, as I originally thought.
Anyway here my logs:
[Logs.zip](https://github.com/zegreatclan/SimHub/files/3365736/Logs.zip)
I'm running Win10 x64 1809.
Thanks!

**Comment by zegreatclan** [comment]
Found it ! Indeed there was a small leak in shakeit, and like water leaks, a small leak can waste a lot with enough time (or enough effects) !

**Comment by Romainrob** [comment]
I'm running a lot of effects... for hours on end. I guess I'm in a worst case scenario.
Yet it still didn't happened very often. 
Anyway. Thanks you for fixing it.

**Comment by zegreatclan** [comment]
Yeah indeed the more effects the worst it was, hopefully with the right tools this leak was easy to spot.

**Comment by zegreatclan** [comment]
Fix released with simhub 6.8.2 ;)
