### ISSUE TITLE
Freeze/crash with high cpu usage

### ISSUE THREAD

**Issue by pokornyib** [zegreatclan/SimHub#375]
The SimHub freezes after some time with high (50%) CPU usage. In this satate I cannot even close the SimHub.
Game: iRacing
Used things: Nextion display with FT232 and an arduino with 16pcs of ws2812 LED
Changed settings: 

- high processor priority enabled
- controllers input disabled from plugins.
- thrustmaster FFB control disabled  from plugins.
- afterburner connector disabled from plugins

![simHub_crash_log](https://user-images.githubusercontent.com/31725684/60913021-d1c24d00-a286-11e9-9b86-13a44092701d.JPG)
![simHub_cpu](https://user-images.githubusercontent.com/31725684/60913024-d1c24d00-a286-11e9-8e87-b06c3bf50d6e.JPG)

Log:
[SimHub.log](https://github.com/zegreatclan/SimHub/files/3374294/SimHub.log)

**Comment by zegreatclan** [comment]
Hi ! Could you try to update your simhub first ? There have been 10 versions released since and the issue have probablt already been solved , You can download the latest simhub version here : https://www.simhubdash.com/download-2/

**Comment by zegreatclan** [comment]
HI ! I close the issue for now, do not hesitate to notify me if you have any new infos.
Best Regards, 
Nicolas (Wotever)
