### ISSUE TITLE
SimHub freezes when I click on iRacing.

### ISSUE THREAD

**Issue by MrPumpkinPie505** [zegreatclan/SimHub#379]
When I click on iRacing to see if my tachometer works everything on simhub freezes and I cant click on anything on simhub.

**Comment by zegreatclan** [comment]
Hi ! Could you join the log files ? Without I'm afraid I'm totally blind ;) the log files are stored inside the log folder inside the simhub install directory.

**Comment by zegreatclan** [comment]
HI ! I close the issue for now, do not hesitate to notify me if you have the log files.
Best Regards, 
Nicolas (Wotever)
