### ISSUE TITLE
full screen mode 

### ISSUE THREAD

**Issue by Nobby910** [zegreatclan/SimHub#380]
how do i enable full screen without the white taskbar that takes up a lot of my screen?

**Comment by zegreatclan** [comment]
Hi ! 
Fullscreen is handled by the browser, the result may vary depending of the device firmware (website fullscreen may differ from video fullscreen) Your device firmware (android) determines how it will behave.

Alternatiely you can use the experimental app on android which forces fullscreen (once again as much as the device supports).

**Comment by Nobby910** [comment]
thanks have now returned my android 9 phone which i bought 2 days ago the
manufacturer had its own rom on it as well as android and was impossible to
get rid of the task bar on it so returned for refund ,
Simhubs now working full screen bought a honor 9 lite on android 9 pie,
simhub now works full screen thanks.
P.S. "fyoi"The android phone I returned , which does not go full screen is
a CUBIT R15 running android 9 pie
did not know there is a experimental app on android which forces fullscreen
oh well
thanks
