### ISSUE TITLE
SimHub not working with Project Cars 2

### ISSUE THREAD

**Issue by dkemery** [zegreatclan/SimHub#382]
I downloaded and installed the new SimHub software on my desktop computer for the first time. In the past I used my gaming laptop with your old software and had no problem. This time around with the new software and desktop computer I couldn't get Project Cars 2 to work with the buttkicker 2, it worked just fine with Assetto Corsa. I changed in the Project Cars 2 interface what you said needed configured from the screen shot you provided. When the game is running your SimHub software says connected when playing Project Cars 2.  Somehow something is not working between the game software and SimHub. Since Assetto Corsa works, it isn't a firewall or virus scan issue, I turn those off anyhow.  I also use Crew Chief software and it works with the game.  It must be something specific to Project Cars 2.  I had running on my PC was Oculus Rift software, Steam, and SimHub., PC2 just wouldn't work but Assetto Corsa did.  I didn't want you to think CrewChief was conflicting.

**Comment by KarlSteeg** [comment]
hi

did you set your pcars2 udp?
ive found that can give alot of issues  i run my udp in pcars1 mode, its alot more stable even if i loose out on a few bits of info, all the important stuff works,

also play with the udp frequency

**Comment by dkemery** [comment]
I set it up as it was shown in their instruction
Shared Memory - Project Cars 2
UDP Frequency - OFF
UDP Protocol Version - Project Cars 1

**Comment by KarlSteeg** [comment]
ive had to put my UDP frequency on 1 or 3 then it works,
but some guys have said setting UDP on makes the game unstable online
personally ive seen on difference, games been unstable with UDP off aswel

**Comment by dkemery** [comment]
I GOT IT TO WORK. I INSTALLED THE OLDER VERSION OF SIM HUB AND FOUND PC2 WORKED WITH IT. I THEN UNINSTALLED THE OLD VERSION, DELETED THE SIM HUB FOLDER AND RE-INSTALLED THE NEW VERSION OF SIM HUB MAKING SURE TO INSTALL AS ADMINISTRATOR AND TURNING OFF MY ANTI-VIRUS PROTECTION. I HOPE THIS MIGHT HELP SOMEONE.

**Comment by KarlSteeg** [comment]
awesome.  glad to hear that!!
