### ISSUE TITLE
Programming PL9823 at E36 CLuster

### ISSUE THREAD

**Issue by Autosim112** [zegreatclan/SimHub#383]
Hi I have a question,

I built a E36 Cluster and built some PL9823 RGB LED's in it to make the Dashboard Lights work. My Problem is that BeamNG Drive gives more Values than 1 or  0 in the raw Result which I want to take. Is there any possiblility to program the LED in a way that it's only active when the raw Result is for example 'DL_FULLBEAM' ?
I'm sorry for my bad english, I add some pictures to demonstrate my problem. 

Greetings from Germany,
Daniel

![1](https://user-images.githubusercontent.com/53303789/61875761-a62c9d00-aeeb-11e9-96b9-e184443e9161.png)
![2](https://user-images.githubusercontent.com/53303789/61875762-a62c9d00-aeeb-11e9-955d-4b995f7dbf2d.png)

**Comment by Autosim112** [comment]
I found a way! 

![3](https://user-images.githubusercontent.com/53303789/61906159-03940e80-af2b-11e9-90e2-171df1a526ce.PNG)

**Comment by zegreatclan** [comment]
Hi ! It's possible to extract those flags using JS :
return $prop("DataCorePlugin.GameRawData.DashLights") & 1024

![image](https://user-images.githubusercontent.com/2207331/62484886-73bc5300-b7bb-11e9-843d-1424d81b209f.png)

Here is the list of the "flags" supported (not sure all of them are available in BEAMNG this comes from the LFS specification on which BeamNG data is based.

        //
        // Résumé :
        //     Shift light on.
        DL_SHIFT = 1,
        //
        // Résumé :
        //     Headlights on full beam.
        DL_FULLBEAM = 2,
        //
        // Résumé :
        //     Handbrake on.
        DL_HANDBRAKE = 4,
        //
        // Résumé :
        //     Pit lane speed limiter on.
        DL_PITSPEED = 8,
        //
        // Résumé :
        //     Traction-control on.
        DL_TC = 16,
        //
        // Résumé :
        //     Left turn signal on.
        DL_SIGNAL_L = 32,
        //
        // Résumé :
        //     Right turn signal on.
        DL_SIGNAL_R = 64,
        //
        // Résumé :
        //     Shared turn signal on (hazard lights).
        DL_SIGNAL_ANY = 128,
        //
        // Résumé :
        //     Oil pressure warning on.
        DL_OILWARN = 256,
        //
        // Résumé :
        //     Battery warning light on.
        DL_BATTERY = 512,
        //
        // Résumé :
        //     Anti-lock brakes active.
        DL_ABS = 1024

**Comment by Autosim112** [comment]
Hey, thanks for your Support! I just added the Code to one of the LEDs, but the raw result just shows 0, no matter what I change. Sorry for my late response!

**Comment by Autosim112** [comment]
Ahhhh I understood it! Now it works! Thanks! <3
