### ISSUE TITLE
OBS plug in

### ISSUE THREAD

**Issue by KarlSteeg** [zegreatclan/SimHub#384]
hi hi

is it possible to get an overlay for OBS recording.
so that while im ingame and i want to record a bit i can see that its started recording.
just a smallred dot over my dash screen will be perfect.

and can i get my simhub arduino buttons to start and stop recording??

Karl

**Comment by zegreatclan** [comment]
Hi ! I guess obs accepts keyboard shortcuts, you can use the "keyboard emulator" plugin to make it simulate the appropriate keystrokes : https://github.com/zegreatclan/SimHub/wiki/Additional-Plugin--Keyboard-Emulator-Plugin

**Comment by KarlSteeg** [comment]
and away to see if its started recording?

**Comment by zegreatclan** [comment]
Nothing at my knowledge I'm afraid :(

**Comment by KarlSteeg** [comment]
ok,  was hoping, but totally understand.
thank you for answering a myriad of silly questions.
i just dont get time to learn coding myself

many thanks
