### ISSUE TITLE
Arduino screens trigger events.

### ISSUE THREAD

**Issue by Tigrejor** [zegreatclan/SimHub#387]
Hi, I was wondering, whenever you cross the finish line the screen displays the lap time, configured in Arduino > Screens > LastLap. I was wondering, how do you configure the trigger events or are they pre-configured and there's a set list of names you must put into screens for it work?
Thanks.

**Comment by zegreatclan** [comment]
Hi ! 

You can find all those events mappings here : 
![image](https://user-images.githubusercontent.com/2207331/62479626-2f768600-b7ae-11e9-9f09-b7d7e2b69a6e.png)

They are indeed preconfigured, but you can edit the behaviour if required

**Comment by Tigrejor** [comment]
Hi, thanks for the reply.
I feel like an idiot now that I see it, I searched it on the Arduino section because I didn't notice the Controls and events one!
Thank you very much.

**Comment by zegreatclan** [comment]
No problems ;) have fun !
