### ISSUE TITLE
green flag green flag

### ISSUE THREAD

**Issue by KarlSteeg** [zegreatclan/SimHub#388]
howdy.

how do i get green and code 60 flags working??
code wise??

im using w2812b leds.
and do i have to use a seperate led for each flag.
i cant get yellow and blue to share

karl

**Comment by KarlSteeg** [comment]
basically asking for help with the NCalc of the double yellows(used for code 60/80)
and the NCalc for green flag,   for race start and greed after yellows and code 60/80

i have no idea where to find it ingame to assign it

**Comment by zegreatclan** [comment]
Hi ! You can find examples here for yellow flag https://github.com/zegreatclan/SimHub/wiki/Arduino---some--RGB-leds-configurations-examples

It will work no matter how many leds you will be using.

For green light it's not available as a standard data yet, as most games makes really hard to guess it and does not gives it explicitely sadly that's why you mont find any suitable properties.

**Comment by KarlSteeg** [comment]
Hi Hi
many thanks.

is there data for double yellows from rF2?
ill need that for code 60/80

blue and yellow flag works fine. althou that cannot share an LED.

how do i look into a game to see what data is availible?
eg tire wear in dirt rally2 and double yellow in rF2??

**Comment by zegreatclan** [comment]
About tyre wear it's not available on dr2, the physics model is pretty "basic" and it's not simulated.

Concerning double yellow it's not available from my knowledge in the API (or maybe using a lot of conditions crossing many data's) but the rf2 model is really badly documented about such thing and extracting a simple yellow has been really hard.
For sharing a led if you follow the examples shown on the wiki the condition is put in "enabled" in the mapping, if you do like this you can put many mappings on the same leds. The limitation is that you can show only one data at a time (the last mapping in the list) so you must choose which one will be shown when having both flags at a time by using the appropriate order

**Comment by KarlSteeg** [comment]
hi hi.

understood.
were can i find a list of what the games do give us?

**Comment by zegreatclan** [comment]
Hi ! When you are in the property list you can read the support status :
![image](https://user-images.githubusercontent.com/2207331/62728591-77024980-ba1c-11e9-888b-8032ab94e499.png)

**Comment by KarlSteeg** [comment]
perfect.
thank you.
ill just use the common flags for now until we can get the info out of rF2.
was really hoping for double yellow or code60-80 flags.
i 3d printed this cool housing for my dash, i triangle with flag cutout, inside 4x w2812 leds fit and set them up as yellow and blue flags, missing race start green and double yellow.  side note, black works well aswel.

karl
