### ISSUE TITLE
separating outputs between arduino and forcefeel seat

### ISSUE THREAD

**Issue by michamedia** [zegreatclan/SimHub#389]
Forgive me for this new thread, but I am looking for a way to be notified when this limitation is solved. I just noticed this issue today after completing my wind simulator.
Thanks for this amazing plugin!

From SimHub Wiki:
"Known limitations : currently separating outputs between arduino and forcefeel seat is not possible. Work is in progress to solve this."

**Comment by zegreatclan** [comment]
Hi ! This limitation has been totally removed on the latest simhub version.all outputs are now totally separate and can be assigned the way you want. I'm currently updating all the documentations thats why this old doc is still lying around. You can find the new documentation about channels configuration on the new version here :https://github.com/zegreatclan/SimHub/wiki/ShakeIt-V3-Motors---Output-Configuration

Best regards,
Nicolas (Wotever)

**Comment by michamedia** [comment]
Fantastic! Of course I forgot to update. Thanks a lot.
