### ISSUE TITLE
Arduino Motor Shield

### ISSUE THREAD

**Issue by johnphotoholic** [zegreatclan/SimHub#391]
Hi there
I want to create a Wind-Sim with an Arduino Uno and the Arduino Motorshield. The latest one. It looks like this:
![motorshield](https://user-images.githubusercontent.com/30895033/62894212-9c5cc380-bd4c-11e9-8bdc-81267959ace3.jpg)

Can anybody givbe me a hint what to do? Sorry I'm pretty new into this.

Best and many thanks
John

**Comment by johnphotoholic** [comment]
Sorry to be more specific. I don't know which shield to choose in the Arduino Setup tool.

**Comment by zegreatclan** [comment]
Hi ! I'm affraid this shield is not supported out of box,
You can see the supported boards here on the wiki : https://github.com/zegreatclan/SimHub/wiki/Arduino-Shake-It#wiring

Sadly this board only supports 2 motors and is 4 times more expensive than all the already supported boards which makes it a very bad candidate for out of box support in SimHub.

However reading the arduino doc you could test simple pwm output and set the outputs on D3 and D11 (see: https://store.arduino.cc/arduino-motor-shield-rev3), I'm not 100% sure it will work, but it's worth a try.

![image](https://user-images.githubusercontent.com/2207331/62895510-59501f80-bd4f-11e9-9371-f21b4e1eb16b.png)

Nicolas (Wotever)

**Comment by johnphotoholic** [comment]
Thank you very very much for the reply. Much appreciated. Didn't work though. Tried everything I could I guess.

Will buy another shield now.
