### ISSUE TITLE
TML simulators are missing data

### ISSUE THREAD

**Issue by sjdawson** [zegreatclan/SimHub#896]
Seems like TML have updated their telemetry data feeds, and SimHub is not picking up on some of the additional data that's available. See screenshot and link for more info.

https://steamcommunity.com/sharedfiles/filedetails/?id=2075761906

Left is data from the localhost API, right is what SimHub is reading.

![image](https://user-images.githubusercontent.com/1701603/128933004-df536ac9-20a9-476c-a5ff-b406c9adb0cc.png)

**Comment by sjdawson** [comment]
Probably worth mentioning that this was whilst playing "The Bus", but also has side-effects in "Fernbus" apparently;
https://discord.com/channels/299259397060689920/306850822518734848/874390385730916432

**Comment by SHWotever** [comment]
Hi ! Actually structure haven't really changed but there was a bug with some values braking the simhub engine. It has been fixed a few releases ago. 

Nicolas

**Comment by sjdawson** [comment]
> It has been fixed a few releases ago.

Quick test, confirmed fixed. Thank you. 👍🏻 😃  

![image](https://user-images.githubusercontent.com/1701603/153558648-c909e071-e66c-4990-b4e2-79a9a802ae70.png)
